"""
STORM multi-perspective research interviews for polaris graph.

Implements TRUE STORM interviews based on Stanford arXiv:2402.14207.
Runs BETWEEN search and analyze nodes. Takes initial search results,
conducts simulated expert interviews across multiple perspectives,
and produces enriched evidence plus a hierarchical outline.

Architecture:
  Phase 1: Dynamic Perspective Discovery — LLM generates persona descriptions
  Phase 2: Multi-Round Interview Simulation — per-perspective Q&A with live search
  Phase 3: Outline Generation from Conversations — cluster Q&A into sections

All LLM calls use generate_structured() (NOT reason()) per Kimi K2.5 lesson #1.
All configuration via env vars per LAW VI.
"""

import asyncio
import logging
import os
import time
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator, model_validator

from src.polaris_graph.llm.openrouter_client import OpenRouterClient
from src.polaris_graph.state import ResearchState, STORM_PERSPECTIVES
from src.polaris_graph.tracing import get_tracer

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Configuration (LAW VI: all from env vars with defaults)
# ---------------------------------------------------------------------------

PG_STORM_ENABLED = os.getenv("PG_STORM_ENABLED", "0") == "1"
PG_STORM_PERSPECTIVES_COUNT = int(os.getenv("PG_STORM_PERSPECTIVES_COUNT", "8"))
PG_STORM_ROUNDS_PER_PERSPECTIVE = int(os.getenv("PG_STORM_ROUNDS_PER_PERSPECTIVE", "4"))
PG_STORM_MAX_TIME_SECONDS = int(os.getenv("PG_STORM_MAX_TIME_SECONDS", "600"))
PG_STORM_QUESTIONS_MAX_TOKENS = int(os.getenv("PG_STORM_QUESTIONS_MAX_TOKENS", "1024"))
PG_STORM_ANSWER_MAX_TOKENS = int(os.getenv("PG_STORM_ANSWER_MAX_TOKENS", "2048"))
PG_STORM_OUTLINE_MAX_TOKENS = int(os.getenv("PG_STORM_OUTLINE_MAX_TOKENS", "4096"))
PG_STORM_PERSONA_MAX_TOKENS = int(os.getenv("PG_STORM_PERSONA_MAX_TOKENS", "2048"))
PG_STORM_SEARCH_QUERIES_PER_QUESTION = int(os.getenv("PG_STORM_SEARCH_QUERIES_PER_QUESTION", "3"))
PG_STORM_WEB_RESULTS_PER_QUERY = int(os.getenv("PG_STORM_WEB_RESULTS_PER_QUERY", "5"))


# ---------------------------------------------------------------------------
# Pydantic schemas (local to STORM interviews, not shared)
# ---------------------------------------------------------------------------


class StormPersona(BaseModel):
    """A research persona with an assigned perspective."""

    perspective: str = Field(description="STORM perspective name")
    name: str = Field(description="Persona name, e.g. 'Dr. Sarah Chen'")
    expertise: str = Field(
        description="Description of the persona's expertise and background"
    )
    question_focus: str = Field(
        description="What this persona is most interested in exploring"
    )

    @model_validator(mode="before")
    @classmethod
    def normalize_field_names(cls, data):
        """Handle LLM variant field names and nulls."""
        if isinstance(data, dict):
            for alt in ("expert_name", "persona_name", "full_name"):
                if alt in data and "name" not in data:
                    data["name"] = data.pop(alt)
            for alt in ("background", "expert_background", "expertise_description"):
                if alt in data and "expertise" not in data:
                    data["expertise"] = data.pop(alt)
            for alt in ("focus", "research_focus", "primary_interest", "focus_area"):
                if alt in data and "question_focus" not in data:
                    data["question_focus"] = data.pop(alt)
            _null_defaults = {
                "perspective": "Scientific",
                "name": "Expert",
                "expertise": "",
                "question_focus": "",
            }
            for field_name, default in _null_defaults.items():
                if data.get(field_name) is None:
                    data[field_name] = default
        return data


class StormPersonaBatch(BaseModel):
    """Batch of STORM personas generated by LLM."""

    personas: list[StormPersona] = Field(
        description="List of research personas, one per perspective",
        default_factory=list,
    )

    @model_validator(mode="before")
    @classmethod
    def normalize_field_names(cls, data):
        """Handle LLM variant names."""
        if isinstance(data, dict):
            for alt in ("experts", "perspectives", "persona_list", "characters"):
                if alt in data and "personas" not in data:
                    data["personas"] = data.pop(alt)
            if data.get("personas") is None:
                data["personas"] = []
        return data

    @model_validator(mode="before")
    @classmethod
    def filter_invalid_personas(cls, data):
        """Skip personas that fail validation."""
        if isinstance(data, dict) and "personas" in data and isinstance(data["personas"], list):
            valid = []
            for item in data["personas"]:
                if not isinstance(item, dict):
                    continue
                try:
                    StormPersona.model_validate(item)
                    valid.append(item)
                except Exception as exc:
                    logger.warning(
                        "[STORM] Dropped invalid persona '%s': %s",
                        item.get("name", "?")[:40],
                        str(exc)[:200],
                    )
            data["personas"] = valid
        return data


class StormQuestion(BaseModel):
    """A question generated by a persona, with decomposed search queries."""

    question: str = Field(description="The research question to ask")
    search_queries: list[str] = Field(
        description="2-3 web search queries to find answer material",
        default_factory=list,
    )
    perspective: str = Field(
        description="STORM perspective this question targets",
        default="Scientific",
    )

    @model_validator(mode="before")
    @classmethod
    def normalize_field_names(cls, data):
        """Handle LLM variant names."""
        if isinstance(data, dict):
            for alt in ("queries", "web_queries", "search_terms"):
                if alt in data and "search_queries" not in data:
                    data["search_queries"] = data.pop(alt)
            if data.get("question") is None:
                data["question"] = ""
            if data.get("search_queries") is None:
                data["search_queries"] = []
            if data.get("perspective") is None:
                data["perspective"] = "Scientific"
        return data


class StormAnswer(BaseModel):
    """An expert answer grounded in search results."""

    answer: str = Field(description="Synthesized answer grounded in evidence")
    key_findings: list[str] = Field(
        description="3-5 key findings extracted from search results",
        default_factory=list,
    )
    sources_used: list[str] = Field(
        description="URLs of sources referenced in the answer",
        default_factory=list,
    )

    @model_validator(mode="before")
    @classmethod
    def normalize_field_names(cls, data):
        """Handle LLM variant names."""
        if isinstance(data, dict):
            for alt in ("response", "expert_answer", "synthesized_answer"):
                if alt in data and "answer" not in data:
                    data["answer"] = data.pop(alt)
            for alt in ("findings", "main_findings", "key_points"):
                if alt in data and "key_findings" not in data:
                    data["key_findings"] = data.pop(alt)
            for alt in ("sources", "urls", "references", "cited_sources"):
                if alt in data and "sources_used" not in data:
                    data["sources_used"] = data.pop(alt)
            if data.get("answer") is None:
                data["answer"] = ""
            if data.get("key_findings") is None:
                data["key_findings"] = []
            if data.get("sources_used") is None:
                data["sources_used"] = []
        return data


class StormConversation(BaseModel):
    """A full conversation between a persona and an expert."""

    perspective: str = Field(description="STORM perspective for this conversation")
    persona_name: str = Field(description="Name of the interviewing persona")
    rounds: list[dict] = Field(
        description="List of {question, answer, sources, key_findings} round dicts",
        default_factory=list,
    )

    @model_validator(mode="before")
    @classmethod
    def normalize_field_names(cls, data):
        """Handle LLM variant names."""
        if isinstance(data, dict):
            for alt in ("name", "expert_name", "persona"):
                if alt in data and "persona_name" not in data:
                    data["persona_name"] = data.pop(alt)
            if data.get("perspective") is None:
                data["perspective"] = "Scientific"
            if data.get("persona_name") is None:
                data["persona_name"] = "Expert"
            if data.get("rounds") is None:
                data["rounds"] = []
        return data


class StormOutlineSection(BaseModel):
    """A section in the STORM-generated outline."""

    title: str = Field(description="Section title")
    description: str = Field(description="What this section covers")
    evidence_summary: str = Field(
        description="Summary of evidence from conversations for this section",
        default="",
    )
    perspectives: list[str] = Field(
        description="STORM perspectives that contributed to this section",
        default_factory=list,
    )
    order: int = Field(description="Order in the outline", default=0)

    @field_validator("evidence_summary", mode="before")
    @classmethod
    def coerce_evidence_summary(cls, v):
        """RC-7: Belt-and-suspenders coercion for evidence_summary.

        LLM sometimes returns list/dict despite prompt saying string.
        normalize_field_names handles dict-level, this handles Pydantic-level.
        """
        if v is None:
            return ""
        if isinstance(v, list):
            return "; ".join(str(item)[:200] for item in v if item)
        if isinstance(v, dict):
            return "; ".join(f"{k}: {val}" for k, val in v.items())[:1000]
        if not isinstance(v, str):
            return str(v)[:1000]
        return v

    @model_validator(mode="before")
    @classmethod
    def normalize_field_names(cls, data):
        """Handle LLM variant names."""
        if isinstance(data, dict):
            for alt in ("section_title", "heading", "name"):
                if alt in data and "title" not in data:
                    data["title"] = data.pop(alt)
            for alt in ("content_description", "section_description", "summary"):
                if alt in data and "description" not in data:
                    data["description"] = data.pop(alt)
            for alt in ("evidence", "supporting_evidence", "evidence_from_conversations"):
                if alt in data and "evidence_summary" not in data:
                    data["evidence_summary"] = data.pop(alt)
            for alt in ("covered_perspectives", "perspective_list", "storm_perspectives"):
                if alt in data and "perspectives" not in data:
                    data["perspectives"] = data.pop(alt)
            for alt in ("section_order", "position", "index"):
                if alt in data and "order" not in data:
                    data["order"] = data.pop(alt)
            if data.get("title") is None:
                data["title"] = ""
            if data.get("description") is None:
                data["description"] = ""
            # FIX-STORM-TYPE: Coerce list/dict to string
            ev_summary = data.get("evidence_summary")
            if ev_summary is None:
                data["evidence_summary"] = ""
            elif isinstance(ev_summary, list):
                data["evidence_summary"] = "; ".join(
                    str(item)[:200] for item in ev_summary if item
                )
            elif isinstance(ev_summary, dict):
                data["evidence_summary"] = "; ".join(
                    f"{k}: {v}" for k, v in ev_summary.items()
                )[:1000]
            elif not isinstance(ev_summary, str):
                data["evidence_summary"] = str(ev_summary)[:1000]
            if data.get("perspectives") is None:
                data["perspectives"] = []
            if data.get("order") is None:
                data["order"] = 0
        return data


class StormOutlinePlan(BaseModel):
    """Complete outline generated from STORM conversations."""

    sections: list[StormOutlineSection] = Field(
        description="Ordered sections for the research report",
        default_factory=list,
    )

    @model_validator(mode="before")
    @classmethod
    def normalize_field_names(cls, data):
        """Handle LLM variant names."""
        if isinstance(data, dict):
            for alt in ("outline", "outline_sections", "section_list", "report_sections"):
                if alt in data and "sections" not in data:
                    data["sections"] = data.pop(alt)
            if data.get("sections") is None:
                data["sections"] = []
        return data

    @model_validator(mode="before")
    @classmethod
    def filter_invalid_sections(cls, data):
        """Skip sections that fail validation."""
        if isinstance(data, dict) and "sections" in data and isinstance(data["sections"], list):
            valid = []
            for i, item in enumerate(data["sections"]):
                if not isinstance(item, dict):
                    continue
                if "order" not in item and "section_order" not in item:
                    item["order"] = i + 1
                try:
                    StormOutlineSection.model_validate(item)
                    valid.append(item)
                except Exception as exc:
                    logger.warning(
                        "[STORM] Dropped invalid outline section '%s': %s",
                        item.get("title", "?")[:40],
                        str(exc)[:200],
                    )
            data["sections"] = valid
        return data


# ---------------------------------------------------------------------------
# Search integration — reuse existing search infrastructure
# ---------------------------------------------------------------------------


def _import_search_tools():
    """Import search tools from existing infrastructure."""
    from src.polaris_graph.agents.searcher import _run_web_searches, _import_search_tools as _get_tools

    return _run_web_searches, _get_tools


async def _search_for_question(
    question_queries: list[str],
    region: str,
    perspective: str = "",
) -> list[dict]:
    """Execute web searches for a STORM interview question.

    Reuses the battle-tested _run_web_searches from searcher.py with
    a concurrency-limited semaphore. Returns raw search result dicts.
    """
    if not question_queries:
        return []

    try:
        from src.polaris_graph.agents.searcher import _run_web_searches, _import_search_tools

        web_search_fn, _ = _import_search_tools()
        results = await _run_web_searches(web_search_fn, question_queries, region)

        # Tag results as originating from STORM interviews
        for r in results:
            r["storm_interview"] = True
            if perspective:
                r["perspective_source"] = perspective

        return results

    except Exception as exc:
        logger.warning(
            "[STORM] Search failed for queries %s: %s",
            [q[:40] for q in question_queries[:3]],
            str(exc)[:200],
        )
        return []


# ---------------------------------------------------------------------------
# Phase 1: Dynamic Perspective Discovery
# ---------------------------------------------------------------------------


async def _discover_perspectives(
    client: OpenRouterClient,
    query: str,
    existing_context: str,
    target_count: int,
) -> list[StormPersona]:
    """Generate diverse research personas based on the topic.

    Uses the base STORM_PERSPECTIVES as guidance but generates unique
    persona descriptions with specific expertise relevant to the query.
    Post-processes with _dedup_personas to eliminate >70% word overlap.

    Args:
        client: OpenRouter LLM client.
        query: The original research question.
        existing_context: Snippets from initial search results for grounding.
        target_count: Number of personas to generate.

    Returns:
        List of StormPersona objects, one per perspective.
    """
    # Select perspectives (cap to target_count)
    perspectives_to_use = STORM_PERSPECTIVES[:target_count]

    perspective_descriptions = "\n".join(
        f"  {i+1}. {p}" for i, p in enumerate(perspectives_to_use)
    )

    prompt = (
        f"You are designing a multi-perspective research team to investigate "
        f"a complex research question through simulated expert interviews.\n\n"
        f"RESEARCH QUESTION: {query}\n\n"
        f"INITIAL RESEARCH CONTEXT (from preliminary search):\n{existing_context}\n\n"
        f"Create exactly {target_count} expert personas, one for each of these "
        f"research perspectives:\n{perspective_descriptions}\n\n"
        f"DIVERSITY REQUIREMENTS (CRITICAL):\n"
        f"- Each persona MUST have a DIFFERENT primary discipline. Do NOT repeat "
        f"disciplines across personas.\n"
        f"- Ensure at least one persona from each of: hard science (physics, "
        f"chemistry, biology, engineering), social science (sociology, psychology, "
        f"anthropology), economics/finance, policy/regulation, industry/practice, "
        f"and public health — as applicable to the research question.\n"
        f"- Each expertise description MUST use DIFFERENT technical vocabulary. "
        f"If two personas share >50% of their terminology, they are NOT distinct "
        f"enough.\n"
        f"- Vary methodological approaches: quantitative vs qualitative, "
        f"experimental vs observational, micro vs macro, theoretical vs applied.\n\n"
        f"For each persona, provide:\n"
        f"- perspective: The exact perspective name from the list above\n"
        f"- name: A realistic expert name (e.g., 'Dr. Maria Rodriguez')\n"
        f"- expertise: 2-3 sentences describing their specific domain expertise, "
        f"academic background, and why their viewpoint matters for this topic. "
        f"Make it specific to the research question, not generic.\n"
        f"- question_focus: What specific aspect of the research question this "
        f"expert would focus on. Be concrete — cite specific subtopics, "
        f"methodologies, or data types they would look for.\n\n"
        f"Make each persona distinct. Their expertise should NOT overlap. "
        f"Together they should cover the full landscape of the research question.\n\n"
        f"Return a JSON object with a 'personas' array."
    )

    try:
        result = await client.generate_structured(
            prompt=prompt,
            schema=StormPersonaBatch,
            max_tokens=PG_STORM_PERSONA_MAX_TOKENS,
            reasoning_enabled=False,
        )

        if result and result.personas:
            logger.info(
                "[STORM] Phase 1: Generated %d personas for %d perspectives",
                len(result.personas),
                target_count,
            )
            for persona in result.personas:
                logger.debug(
                    "[STORM]   %s (%s): %s",
                    persona.name,
                    persona.perspective,
                    persona.question_focus[:80],
                )
            return _dedup_personas(result.personas, query)

    except Exception as exc:
        logger.warning(
            "[STORM] Phase 1: Persona generation failed: %s — using fallback personas",
            str(exc)[:200],
        )

    # Fallback: generate basic personas without LLM
    return _fallback_personas(perspectives_to_use, query)


def _dedup_personas(
    personas: list[StormPersona],
    query: str,
) -> list[StormPersona]:
    """Remove personas with >70% word overlap in expertise fields.

    Compares each pair of personas by tokenizing their expertise description
    into word sets and computing overlap ratio against the smaller set.
    If overlap exceeds the threshold, the second persona is dropped and a
    warning is logged.

    Args:
        personas: List of generated personas.
        query: Original research question (for logging context).

    Returns:
        Deduplicated list of personas.
    """
    if len(personas) <= 1:
        return personas

    dedup_threshold = float(os.getenv("PG_STORM_PERSONA_DEDUP_THRESHOLD", "0.70"))
    deduped: list[StormPersona] = []
    dropped_count = 0

    for persona in personas:
        words_new = set(persona.expertise.lower().split())
        is_duplicate = False

        for existing in deduped:
            words_existing = set(existing.expertise.lower().split())
            if not words_new or not words_existing:
                continue
            intersection = words_new & words_existing
            smaller_set_size = min(len(words_new), len(words_existing))
            if smaller_set_size == 0:
                continue
            overlap = len(intersection) / smaller_set_size
            if overlap > dedup_threshold:
                logger.warning(
                    "[STORM] Persona dedup: dropping '%s' (%s) — %.0f%% word "
                    "overlap with '%s' (%s) in expertise field",
                    persona.name,
                    persona.perspective,
                    overlap * 100,
                    existing.name,
                    existing.perspective,
                )
                is_duplicate = True
                dropped_count += 1
                break

        if not is_duplicate:
            deduped.append(persona)

    if dropped_count > 0:
        logger.info(
            "[STORM] Persona dedup: kept %d/%d personas (dropped %d with >%.0f%% overlap) "
            "for query: %s",
            len(deduped),
            len(personas),
            dropped_count,
            dedup_threshold * 100,
            query[:80],
        )

    return deduped


def _fallback_personas(
    perspectives: list[str],
    query: str,
) -> list[StormPersona]:
    """Generate fallback personas when LLM fails.

    Creates template-based personas that are functional but less nuanced
    than LLM-generated ones.
    """
    fallback_names = {
        "Scientific": "Dr. Sarah Chen",
        "Regulatory": "James Morrison, JD",
        "Industry": "Patricia Nakamura",
        "Economic": "Dr. Robert Okafor",
        "Public_Health": "Dr. Maria Gonzalez",
        "Historical": "Prof. David Whitfield",
        "Regional": "Anika Patel",
        "Methodological": "Dr. Kenji Tanaka",
        "Emerging_Trends": "Dr. Elisa Ferreira",
    }

    fallback_expertise = {
        "Scientific": "peer-reviewed research methodology and experimental design",
        "Regulatory": "regulatory frameworks, compliance standards, and policy analysis",
        "Industry": "market applications, commercial viability, and industry adoption",
        "Economic": "cost-benefit analysis, market dynamics, and economic impact",
        "Public_Health": "population health outcomes, epidemiology, and health equity",
        "Historical": "historical development, evolution of practices, and precedent analysis",
        "Regional": "geographic variations, regional implementations, and local context",
        "Methodological": "research methods, measurement techniques, and analytical frameworks",
        "Emerging_Trends": "frontier developments, emerging technologies, and future directions",
    }

    personas = []
    for perspective in perspectives:
        name = fallback_names.get(perspective, f"Expert ({perspective})")
        expertise = fallback_expertise.get(perspective, f"expertise in {perspective.lower()}")

        personas.append(StormPersona(
            perspective=perspective,
            name=name,
            expertise=f"Specialist in {expertise} with focus on topics related to: {query[:100]}",
            question_focus=f"Investigating the {perspective.lower().replace('_', ' ')} "
                           f"dimensions of the research question.",
        ))

    logger.info(
        "[STORM] Phase 1 fallback: Generated %d template personas",
        len(personas),
    )
    return personas


# ---------------------------------------------------------------------------
# Phase 2: Multi-Round Interview Simulation
# ---------------------------------------------------------------------------


async def _generate_question(
    client: OpenRouterClient,
    persona: StormPersona,
    query: str,
    conversation_history: list[dict],
    round_number: int,
) -> Optional[StormQuestion]:
    """Generate a targeted question from a persona's perspective.

    Uses the persona's expertise and prior conversation rounds to generate
    a progressively deeper question. Round 1 is broad; later rounds drill
    into gaps identified in previous answers.

    Args:
        client: OpenRouter LLM client.
        persona: The interviewing persona.
        query: Original research question.
        conversation_history: Previous rounds of {question, answer} dicts.
        round_number: Current round (1-indexed).

    Returns:
        StormQuestion with the question and decomposed search queries,
        or None if generation fails.
    """
    history_context = ""
    if conversation_history:
        history_lines = []
        for i, rnd in enumerate(conversation_history, 1):
            history_lines.append(
                f"Round {i}:\n"
                f"  Q: {rnd.get('question', '')[:200]}\n"
                f"  A: {rnd.get('answer', '')[:300]}"
            )
        history_context = (
            f"\nPREVIOUS CONVERSATION ROUNDS:\n"
            + "\n".join(history_lines)
            + "\n"
        )

    round_guidance = ""
    if round_number == 1:
        round_guidance = (
            "This is the FIRST question. Ask a broad, foundational question "
            "that establishes the key facts and current state of knowledge "
            "from your perspective."
        )
    elif round_number == 2:
        round_guidance = (
            "This is the SECOND question. Based on the first answer, identify "
            "a specific gap or surprising finding and drill deeper into it."
        )
    elif round_number == 3:
        round_guidance = (
            "This is the THIRD question. Look for contradictions, nuances, "
            "or under-explored aspects. Ask about methodology, data quality, "
            "or alternative interpretations."
        )
    else:
        round_guidance = (
            f"This is round {round_number}. Ask about the most important "
            f"remaining gap in your understanding. Focus on what is still "
            f"UNKNOWN or CONTESTED, not what has already been well-answered."
        )

    prompt = (
        f"You are {persona.name}, an expert in {persona.expertise}.\n\n"
        f"You are conducting a research interview about:\n"
        f"RESEARCH QUESTION: {query}\n\n"
        f"Your perspective: {persona.perspective}\n"
        f"Your focus area: {persona.question_focus}\n"
        f"{history_context}\n"
        f"{round_guidance}\n\n"
        f"Generate:\n"
        f"1. ONE focused, specific research question from your expert perspective. "
        f"Do NOT repeat questions already asked. The question should be answerable "
        f"through web/academic search — avoid purely philosophical or speculative questions.\n"
        f"2. Exactly {PG_STORM_SEARCH_QUERIES_PER_QUESTION} web search queries that "
        f"would help find the answer. Use precise, search-engine-friendly language. "
        f"Include at least one query with specific technical terms or named entities.\n\n"
        f"Return a JSON object with 'question', 'search_queries', and 'perspective' fields."
    )

    try:
        result = await client.generate_structured(
            prompt=prompt,
            schema=StormQuestion,
            max_tokens=PG_STORM_QUESTIONS_MAX_TOKENS,
            reasoning_enabled=False,
        )

        if result and result.question:
            # Enforce search query count limit
            result.search_queries = result.search_queries[:PG_STORM_SEARCH_QUERIES_PER_QUESTION]
            logger.debug(
                "[STORM] %s (round %d) asks: %s [%d queries]",
                persona.name,
                round_number,
                result.question[:100],
                len(result.search_queries),
            )
            return result

    except Exception as exc:
        logger.warning(
            "[STORM] Question generation failed for %s round %d: %s",
            persona.name,
            round_number,
            str(exc)[:200],
        )

    return None


async def _synthesize_answer(
    client: OpenRouterClient,
    persona: StormPersona,
    question: str,
    search_results: list[dict],
    query: str,
) -> Optional[StormAnswer]:
    """Synthesize an expert answer grounded in search results.

    The LLM acts as a knowledgeable expert responding to the persona's
    question, but ONLY using information from the provided search results.
    No hallucination allowed.

    Args:
        client: OpenRouter LLM client.
        persona: The persona who asked the question (for context).
        question: The question to answer.
        search_results: Web search results to ground the answer in.
        query: Original research question for relevance context.

    Returns:
        StormAnswer with synthesized answer and key findings,
        or None if synthesis fails.
    """
    # Build search context from results
    context_lines = []
    source_urls = []
    for i, r in enumerate(search_results[:15], 1):
        title = r.get("title", "Untitled")
        snippet = r.get("snippet", "")[:400]
        url = r.get("url", "")
        source_urls.append(url)
        context_lines.append(
            f"[Source {i}] {title}\n"
            f"  URL: {url}\n"
            f"  Content: {snippet}"
        )

    if not context_lines:
        logger.warning(
            "[STORM] No search results to ground answer for: %s",
            question[:80],
        )
        return None

    search_context = "\n".join(context_lines)

    prompt = (
        f"You are a research expert being interviewed about:\n"
        f"RESEARCH QUESTION: {query}\n\n"
        f"The interviewer ({persona.name}, {persona.perspective} perspective) asks:\n"
        f"QUESTION: {question}\n\n"
        f"SEARCH RESULTS (your ONLY source of information):\n{search_context}\n\n"
        f"INSTRUCTIONS:\n"
        f"1. Provide a comprehensive, well-structured answer (200-400 words).\n"
        f"2. ONLY use information from the search results above. Do NOT add "
        f"information not present in the sources.\n"
        f"3. When citing specific facts, mention which source they come from.\n"
        f"4. Extract 3-5 key findings as bullet points.\n"
        f"5. List the URLs of sources you actually used in your answer.\n"
        f"6. If the search results do not adequately answer the question, "
        f"say so explicitly and note what information is missing.\n\n"
        f"Return a JSON object with 'answer', 'key_findings', and 'sources_used' fields."
    )

    try:
        result = await client.generate_structured(
            prompt=prompt,
            schema=StormAnswer,
            max_tokens=PG_STORM_ANSWER_MAX_TOKENS,
            reasoning_enabled=False,
        )

        if result and result.answer:
            logger.debug(
                "[STORM] Answer synthesized: %d chars, %d findings, %d sources",
                len(result.answer),
                len(result.key_findings),
                len(result.sources_used),
            )
            return result

    except Exception as exc:
        logger.warning(
            "[STORM] Answer synthesis failed for question '%s': %s",
            question[:60],
            str(exc)[:200],
        )

    return None


async def _conduct_interview(
    client: OpenRouterClient,
    persona: StormPersona,
    query: str,
    region: str,
    max_rounds: int,
    time_budget_remaining: float,
) -> tuple[StormConversation, list[dict]]:
    """Conduct a multi-round interview with a single persona.

    Each round: persona asks -> search -> expert answers.
    Accumulates conversation history and all search results.

    Args:
        client: OpenRouter LLM client.
        persona: The interviewing persona.
        query: Original research question.
        region: Search region.
        max_rounds: Maximum interview rounds.
        time_budget_remaining: Seconds remaining in total STORM budget.

    Returns:
        Tuple of (StormConversation, list of all search results from this interview).
    """
    conversation = StormConversation(
        perspective=persona.perspective,
        persona_name=persona.name,
        rounds=[],
    )
    all_search_results: list[dict] = []
    interview_start = time.monotonic()

    # FIX-1: Use the caller's fair-shared budget directly (no further halving).
    # The caller already computed: remaining / perspectives_remaining.
    per_interview_budget = time_budget_remaining

    for round_num in range(1, max_rounds + 1):
        elapsed = time.monotonic() - interview_start
        if elapsed > per_interview_budget:
            logger.info(
                "[STORM] %s interview: time budget exhausted at round %d/%.0fs",
                persona.name,
                round_num,
                elapsed,
            )
            break

        # Step 1: Generate question
        question_obj = await _generate_question(
            client=client,
            persona=persona,
            query=query,
            conversation_history=conversation.rounds,
            round_number=round_num,
        )

        if not question_obj or not question_obj.question:
            logger.warning(
                "[STORM] %s round %d: question generation failed, stopping interview",
                persona.name,
                round_num,
            )
            break

        # Step 2: Execute search with decomposed queries
        # WARN-1 FIX: Pass perspective so results carry perspective_source tag
        round_results = await _search_for_question(
            question_queries=question_obj.search_queries,
            region=region,
            perspective=persona.perspective,
        )
        all_search_results.extend(round_results)

        logger.info(
            "[STORM] %s round %d: searched %d queries -> %d results",
            persona.name,
            round_num,
            len(question_obj.search_queries),
            len(round_results),
        )

        # Step 3: Synthesize answer grounded in search results
        answer_obj = await _synthesize_answer(
            client=client,
            persona=persona,
            question=question_obj.question,
            search_results=round_results,
            query=query,
        )

        if not answer_obj:
            logger.warning(
                "[STORM] %s round %d: answer synthesis failed, recording question only",
                persona.name,
                round_num,
            )
            # Record the question even if answer failed (partial data)
            conversation.rounds.append({
                "question": question_obj.question,
                "answer": "[Answer synthesis failed — no search results or LLM error]",
                "sources": [],
                "key_findings": [],
            })
            continue

        # FIX-P2: Detect STORM interview failures — answers that explicitly state
        # sources are inadequate should not pollute the evidence pool.
        _failure_patterns = (
            "do not adequately",
            "does not adequately",
            "do NOT",
            "data is incomplete",
            "not directly reported",
            "none of the sources directly",
            "sources do not provide",
            "no specific data",
            "insufficient information",
            "cannot be determined from",
        )
        _answer_lower = answer_obj.answer.lower() if answer_obj.answer else ""
        _is_failed_interview = any(fp.lower() in _answer_lower for fp in _failure_patterns)

        # Record the round (with failure flag)
        conversation.rounds.append({
            "question": question_obj.question,
            "answer": answer_obj.answer,
            "sources": answer_obj.sources_used,
            "key_findings": answer_obj.key_findings if not _is_failed_interview else [],
            "interview_quality": "failed" if _is_failed_interview else "ok",
        })
        if _is_failed_interview:
            logger.info(
                "[STORM] FIX-P2: %s round %d marked FAILED — answer indicates "
                "inadequate sources. key_findings cleared.",
                persona.name, round_num,
            )

        # OBS-STORM: Emit full Q&A to trace
        _storm_tracer = get_tracer()
        if _storm_tracer:
            _storm_tracer.storm_transcript(
                persona=persona.name,
                round_num=round_num,
                question=question_obj.question,
                answer=answer_obj.answer,
                sources=answer_obj.sources_used,
                key_findings=answer_obj.key_findings if not _is_failed_interview else [],
                expertise=persona.expertise[:200],
                question_focus=persona.question_focus[:200],
                interview_quality="failed" if _is_failed_interview else "ok",
            )

    logger.info(
        "[STORM] %s interview complete: %d rounds, %d total search results",
        persona.name,
        len(conversation.rounds),
        len(all_search_results),
    )

    # WAVE-4.5: Per-persona interview complete trace
    _storm_tracer = get_tracer()
    if _storm_tracer:
        _storm_tracer.llm_call("storm_interviews", "interview_complete",
            persona_name=persona.name,
            perspective=persona.perspective,
            rounds_completed=len(conversation.rounds),
            search_results=len(all_search_results),
            qa_pairs=len(conversation.rounds))

    return conversation, all_search_results


# ---------------------------------------------------------------------------
# Phase 3: Outline Generation from Conversations
# ---------------------------------------------------------------------------


async def _generate_outline_from_conversations(
    client: OpenRouterClient,
    query: str,
    conversations: list[StormConversation],
) -> list[dict]:
    """Generate a hierarchical outline from STORM conversation clusters.

    Analyzes all Q&A pairs across all perspectives, identifies thematic
    clusters, and produces a structured outline where each section inherits
    evidence from its contributing conversations.

    This is the ONE call that uses reasoning_enabled=True because it requires
    structural thinking to organize diverse conversations into a coherent outline.

    Args:
        client: OpenRouter LLM client.
        query: Original research question.
        conversations: All completed STORM conversations.

    Returns:
        List of outline section dicts (serialized StormOutlineSection).
    """
    if not conversations:
        logger.warning("[STORM] Phase 3: No conversations to generate outline from")
        return []

    # Build conversation digest for the LLM
    digest_lines = []
    total_rounds = 0
    for conv in conversations:
        digest_lines.append(
            f"\n=== {conv.perspective} ({conv.persona_name}) ==="
        )
        for rnd in conv.rounds:
            total_rounds += 1
            question = rnd.get("question", "")[:200]
            answer = rnd.get("answer", "")[:500]
            findings = rnd.get("key_findings", [])
            findings_text = "; ".join(f[:100] for f in findings[:5])
            digest_lines.append(
                f"  Q: {question}\n"
                f"  A: {answer}\n"
                f"  Key findings: {findings_text}"
            )

    conversation_digest = "\n".join(digest_lines)

    # Truncate digest if too long (stay within context window)
    max_digest_chars = 80000  # ~25K tokens, safe for Kimi K2.5 128K context
    if len(conversation_digest) > max_digest_chars:
        conversation_digest = conversation_digest[:max_digest_chars] + "\n[...truncated]"

    perspectives_used = list({conv.perspective for conv in conversations})

    prompt = (
        f"You are a research outline architect. Based on multi-perspective "
        f"expert interviews, create a comprehensive report outline.\n\n"
        f"RESEARCH QUESTION: {query}\n\n"
        f"INTERVIEW CONVERSATIONS ({len(conversations)} perspectives, "
        f"{total_rounds} total Q&A rounds):\n{conversation_digest}\n\n"
        f"PERSPECTIVES COVERED: {', '.join(perspectives_used)}\n\n"
        f"INSTRUCTIONS:\n"
        f"1. Identify 8-15 thematic clusters across ALL conversations.\n"
        f"2. For each cluster, create a report section with:\n"
        f"   - title: Clear, descriptive section heading\n"
        f"   - description: 2-3 sentences on what this section should cover\n"
        f"   - evidence_summary: Key findings from conversations that belong here\n"
        f"   - perspectives: Which STORM perspectives contributed to this section\n"
        f"   - order: Sequential position (1-based)\n"
        f"3. Sections should be ordered logically: background -> methodology -> "
        f"findings -> analysis -> implications -> future directions.\n"
        f"4. Each section should draw from at least 2 different perspectives "
        f"where possible (multi-perspective synthesis).\n"
        f"5. Do NOT create a section for every single Q&A pair — cluster "
        f"related information together.\n"
        f"6. Ensure COMPLETE COVERAGE: every key finding from the interviews "
        f"should appear in at least one section's evidence_summary.\n\n"
        f"Return a JSON object with a 'sections' array of outline section objects."
    )

    try:
        result = await client.generate_structured(
            prompt=prompt,
            schema=StormOutlinePlan,
            max_tokens=PG_STORM_OUTLINE_MAX_TOKENS,
            reasoning_enabled=True,
        )

        if result and result.sections:
            logger.info(
                "[STORM] Phase 3: Generated outline with %d sections from %d conversations",
                len(result.sections),
                len(conversations),
            )
            for section in result.sections:
                logger.debug(
                    "[STORM]   [%d] %s (%d perspectives)",
                    section.order,
                    section.title[:60],
                    len(section.perspectives),
                )
            return [s.model_dump() for s in result.sections]

    except Exception as exc:
        logger.warning(
            "[STORM] Phase 3: Outline generation failed: %s — using fallback",
            str(exc)[:200],
        )

    # Fallback: one section per perspective
    return _fallback_outline(conversations, query)


def _fallback_outline(
    conversations: list[StormConversation],
    query: str,
) -> list[dict]:
    """Generate a simple fallback outline when LLM outline generation fails.

    Creates one section per perspective that had conversations, using the
    conversation key findings as evidence summaries. Functional but less
    nuanced than LLM-generated outlines.
    """
    sections = []
    for i, conv in enumerate(conversations, 1):
        # Collect all key findings from this perspective's conversations
        findings = []
        for rnd in conv.rounds:
            findings.extend(rnd.get("key_findings", []))

        evidence = "; ".join(f[:100] for f in findings[:8])

        sections.append(StormOutlineSection(
            title=f"{conv.perspective.replace('_', ' ')} Perspective",
            description=(
                f"Analysis of {query[:100]} from the "
                f"{conv.perspective.lower().replace('_', ' ')} perspective, "
                f"based on {len(conv.rounds)} interview rounds."
            ),
            evidence_summary=evidence or "No specific findings extracted.",
            perspectives=[conv.perspective],
            order=i,
        ).model_dump())

    logger.info(
        "[STORM] Phase 3 fallback: Generated %d sections (1 per perspective)",
        len(sections),
    )
    return sections


# ---------------------------------------------------------------------------
# Main Entry Point
# ---------------------------------------------------------------------------


async def run_storm_interviews(
    client: OpenRouterClient,
    state: ResearchState,
) -> dict:
    """Execute TRUE STORM multi-perspective research interviews.

    Runs between search and analyze nodes. Takes initial search results,
    conducts simulated expert interviews with diverse personas, and
    produces enriched evidence plus a hierarchical outline.

    The function is idempotent with respect to state — it reads from state
    and returns a dict of state updates (never mutates state directly).

    Args:
        client: OpenRouter LLM client for all LLM calls.
        state: Current ResearchState with search results.

    Returns:
        Dict with state updates:
        - storm_conversations: List of serialized StormConversation dicts.
        - storm_outline: List of serialized StormOutlineSection dicts.
        - web_results: Original + interview-sourced web results.
        - academic_results: Original academic results (pass-through).
    """
    if not PG_STORM_ENABLED:
        logger.info("[STORM] STORM interviews disabled (PG_STORM_ENABLED=0)")
        return {}

    tracer = get_tracer()
    start_time = time.monotonic()
    original_query = state["original_query"]
    region = state["region"]
    web_results = list(state.get("web_results", []))
    academic_results = list(state.get("academic_results", []))

    logger.info(
        "[STORM] Starting STORM interviews for: %s",
        original_query[:100],
    )
    logger.info(
        "[STORM] Config: %d perspectives, %d rounds/perspective, %ds budget",
        PG_STORM_PERSPECTIVES_COUNT,
        PG_STORM_ROUNDS_PER_PERSPECTIVE,
        PG_STORM_MAX_TIME_SECONDS,
    )

    if tracer:
        tracer.node_start(
            "storm_interviews",
            perspectives=PG_STORM_PERSPECTIVES_COUNT,
            rounds_per_perspective=PG_STORM_ROUNDS_PER_PERSPECTIVE,
            time_budget=PG_STORM_MAX_TIME_SECONDS,
            existing_web_results=len(web_results),
            existing_academic_results=len(academic_results),
        )

    # -----------------------------------------------------------------------
    # Phase 1: Dynamic Perspective Discovery
    # -----------------------------------------------------------------------
    logger.info("[STORM] === Phase 1: Perspective Discovery ===")

    # Build context from existing search results for grounding
    existing_context_lines = []
    for r in (web_results + academic_results)[:20]:
        title = r.get("title", "")
        snippet = r.get("snippet", "")[:200]
        if title:
            existing_context_lines.append(f"- {title}: {snippet}")

    existing_context = "\n".join(existing_context_lines) if existing_context_lines else "(no prior results)"

    personas = await _discover_perspectives(
        client=client,
        query=original_query,
        existing_context=existing_context,
        target_count=PG_STORM_PERSPECTIVES_COUNT,
    )

    if not personas:
        logger.error("[STORM] Phase 1: No personas generated — aborting STORM interviews")
        if tracer:
            tracer.node_end("storm_interviews", result="failed", reason="no_personas")
        return {}

    phase_1_elapsed = time.monotonic() - start_time
    logger.info(
        "[STORM] Phase 1 complete: %d personas in %.1fs",
        len(personas),
        phase_1_elapsed,
    )

    if tracer:
        tracer.llm_call(
            "storm_interviews",
            "perspective_discovery",
            personas_generated=len(personas),
            perspectives=[p.perspective for p in personas],
        )

    # -----------------------------------------------------------------------
    # Phase 2: Multi-Round Interview Simulation
    # -----------------------------------------------------------------------
    logger.info("[STORM] === Phase 2: Interview Simulation ===")

    all_conversations: list[StormConversation] = []
    all_interview_results: list[dict] = []
    completed_perspectives: list[str] = []
    skipped_perspectives: list[str] = []

    # FIX-PARALLEL: Run STORM interviews concurrently with semaphore control.
    # Pre-allocate time budget per persona (total budget / persona count).
    # Previous: sequential loop meant later personas got exponentially less time.
    storm_concurrency = int(os.getenv("PG_STORM_CONCURRENCY", "4"))
    storm_sem = asyncio.Semaphore(storm_concurrency)
    per_persona_budget = max(
        60.0,
        (PG_STORM_MAX_TIME_SECONDS - (time.monotonic() - start_time)) / max(len(personas), 1),
    )

    logger.info(
        "[STORM] FIX-PARALLEL: Running %d interviews with concurrency=%d, "
        "%.0fs budget per persona",
        len(personas),
        storm_concurrency,
        per_persona_budget,
    )

    async def _bounded_interview(persona_idx: int, persona: "StormPersona"):
        """Run a single interview bounded by semaphore and time budget."""
        async with storm_sem:
            # Check if global budget is exhausted before starting
            elapsed = time.monotonic() - start_time
            remaining = PG_STORM_MAX_TIME_SECONDS - elapsed
            if remaining <= 30.0:
                logger.warning(
                    "[STORM] Global budget nearly exhausted (%.0fs) — "
                    "skipping %s",
                    remaining,
                    persona.name,
                )
                return persona_idx, None, [], persona.perspective

            logger.info(
                "[STORM] Interview %d/%d: %s (%s) — %.0fs global remaining, "
                "%.0fs budget",
                persona_idx + 1,
                len(personas),
                persona.name,
                persona.perspective,
                remaining,
                per_persona_budget,
            )

            # FIX-058F: Per-interview timeout to prevent hung interviews blocking pipeline
            interview_timeout = int(os.getenv("PG_STORM_INTERVIEW_TIMEOUT", "300"))
            try:
                conversation, interview_results = await asyncio.wait_for(
                    _conduct_interview(
                        client=client,
                        persona=persona,
                        query=original_query,
                        region=region,
                        max_rounds=PG_STORM_ROUNDS_PER_PERSPECTIVE,
                        time_budget_remaining=per_persona_budget,
                    ),
                    timeout=interview_timeout,
                )
                return persona_idx, conversation, interview_results, persona.perspective
            except asyncio.TimeoutError:
                logger.warning(
                    "[STORM] FIX-058F: Interview timed out after %ds for %s (%s) — skipping",
                    interview_timeout,
                    persona.name,
                    persona.perspective,
                )
                # WAVE-4.5: Trace interview timeout
                _to_tracer = get_tracer()
                if _to_tracer:
                    _to_tracer.llm_call("storm_interviews", "interview_failed",
                        persona_name=persona.name, perspective=persona.perspective,
                        persona_index=persona_idx, failure="timeout",
                        timeout_seconds=interview_timeout)
                return persona_idx, None, [], persona.perspective
            except Exception as exc:
                logger.warning(
                    "[STORM] Interview failed for %s (%s): %s — skipping",
                    persona.name,
                    persona.perspective,
                    str(exc)[:200],
                )
                # WAVE-4.5: Trace interview exception
                _ex_tracer = get_tracer()
                if _ex_tracer:
                    _ex_tracer.llm_call("storm_interviews", "interview_failed",
                        persona_name=persona.name, perspective=persona.perspective,
                        persona_index=persona_idx, failure="exception",
                        error=str(exc)[:200])
                return persona_idx, None, [], persona.perspective

    # Launch all interviews
    interview_tasks = [
        _bounded_interview(idx, persona)
        for idx, persona in enumerate(personas)
    ]
    interview_results_raw = await asyncio.gather(*interview_tasks, return_exceptions=True)

    # Collect results in original order
    for result in interview_results_raw:
        if isinstance(result, Exception):
            logger.warning(
                "[STORM] Interview task failed: %s",
                str(result)[:200],
            )
            continue

        persona_idx, conversation, interview_results, perspective = result
        if conversation and conversation.rounds:
            all_conversations.append(conversation)
            all_interview_results.extend(interview_results)
            completed_perspectives.append(perspective)
        else:
            skipped_perspectives.append(perspective)

    phase_2_elapsed = time.monotonic() - start_time
    total_rounds = sum(len(c.rounds) for c in all_conversations)
    total_interview_search_results = len(all_interview_results)

    logger.info(
        "[STORM] Phase 2 complete: %d conversations, %d total rounds, "
        "%d search results in %.1fs",
        len(all_conversations),
        total_rounds,
        total_interview_search_results,
        phase_2_elapsed,
    )

    if skipped_perspectives:
        logger.warning(
            "[STORM] Skipped perspectives: %s",
            ", ".join(skipped_perspectives),
        )

    if tracer:
        tracer.llm_call(
            "storm_interviews",
            "interview_simulation",
            conversations=len(all_conversations),
            total_rounds=total_rounds,
            search_results=total_interview_search_results,
            completed_perspectives=completed_perspectives,
            skipped_perspectives=skipped_perspectives,
        )

    if not all_conversations:
        logger.error("[STORM] Phase 2: No conversations completed — aborting outline")
        if tracer:
            tracer.node_end("storm_interviews", result="failed", reason="no_conversations")
        return {}

    # -----------------------------------------------------------------------
    # Phase 3: Outline Generation from Conversations
    # -----------------------------------------------------------------------

    # Time budget check before Phase 3
    elapsed = time.monotonic() - start_time
    remaining = PG_STORM_MAX_TIME_SECONDS - elapsed

    if remaining <= 15.0:
        logger.warning(
            "[STORM] Time budget too low for outline generation (%.0fs remaining) "
            "— using fallback outline",
            remaining,
        )
        storm_outline = _fallback_outline(all_conversations, original_query)
    else:
        logger.info("[STORM] === Phase 3: Outline Generation ===")
        storm_outline = await _generate_outline_from_conversations(
            client=client,
            query=original_query,
            conversations=all_conversations,
        )

    phase_3_elapsed = time.monotonic() - start_time

    logger.info(
        "[STORM] Phase 3 complete: %d outline sections in %.1fs total",
        len(storm_outline),
        phase_3_elapsed,
    )

    if tracer:
        tracer.llm_call(
            "storm_interviews",
            "outline_generation",
            sections=len(storm_outline),
        )

    # -----------------------------------------------------------------------
    # Assemble state update
    # -----------------------------------------------------------------------

    # Merge interview search results into web_results (they are web searches)
    # Deduplicate by URL before merging
    existing_urls = {r.get("url", "") for r in web_results if r.get("url")}
    new_results = [
        r for r in all_interview_results
        if r.get("url", "") and r.get("url", "") not in existing_urls
    ]
    enriched_web_results = web_results + new_results

    # Serialize conversations
    serialized_conversations = [c.model_dump() for c in all_conversations]

    total_elapsed = time.monotonic() - start_time
    total_llm_calls = (
        1  # Phase 1: persona discovery
        + total_rounds * 2  # Phase 2: question + answer per round
        + 1  # Phase 3: outline generation
    )

    logger.info(
        "[STORM] === STORM Interviews Complete ===\n"
        "  Perspectives: %d completed, %d skipped\n"
        "  Conversations: %d with %d total rounds\n"
        "  New search results: %d (total web: %d)\n"
        "  Outline sections: %d\n"
        "  LLM calls: ~%d\n"
        "  Total time: %.1fs",
        len(completed_perspectives),
        len(skipped_perspectives),
        len(all_conversations),
        total_rounds,
        len(new_results),
        len(enriched_web_results),
        len(storm_outline),
        total_llm_calls,
        total_elapsed,
    )

    if tracer:
        tracer.node_end(
            "storm_interviews",
            result="success",
            conversations=len(all_conversations),
            total_rounds=total_rounds,
            new_search_results=len(new_results),
            outline_sections=len(storm_outline),
            llm_calls=total_llm_calls,
            elapsed_seconds=round(total_elapsed, 1),
            completed_perspectives=completed_perspectives,
            skipped_perspectives=skipped_perspectives,
        )

    return {
        "storm_conversations": serialized_conversations,
        "storm_outline": storm_outline,
        "web_results": enriched_web_results,
        "academic_results": academic_results,
    }
