#!/usr/bin/env python3
"""I-run11-007 (#1051): rank each role model's OpenRouter providers by STABILITY + SPEED and emit
config/settings/openrouter_provider_routing.yaml — the ranked, healthy-only provider order used to
pin every LLM to a stable+fast provider with a deterministic fallback chain that NEVER routes to a
broken server.

Ranking (per the research on /docs provider-selection): keep only operational endpoints
(status==0), then sort by uptime_last_30m desc, latency_last_30m asc, throughput_last_30m desc.
The `order` list is the ranked healthy chain (used with allow_fallbacks:false so off-list flaky
providers are never tried). The `ignore` list is the explicit deny-list of broken endpoints
(status!=0 or uptime below the floor) as belt-and-suspenders.

Reads OPENROUTER_API_KEY from env/.env (never printed). Deterministic given live data. Run from repo root.
"""
from __future__ import annotations
import json, os, sys, urllib.request

UPTIME_FLOOR = float(os.getenv("PG_PROVIDER_UPTIME_FLOOR", "98.0"))
TOP_N = int(os.getenv("PG_PROVIDER_ORDER_TOP_N", "6"))
ROLE_MODELS = {
    "generator": "deepseek/deepseek-v4-pro",
    "mirror": "z-ai/glm-5.1",
    "sentinel": "minimax/minimax-m2",
    "judge": "qwen/qwen3.6-35b-a3b",
}

key = os.getenv("OPENROUTER_API_KEY")
if not key:
    for line in open(".env", encoding="utf-8"):
        if line.startswith("OPENROUTER_API_KEY="):
            key = line.split("=", 1)[1].strip().strip('"').strip("'"); break
if not key:
    print("NO OPENROUTER_API_KEY"); sys.exit(2)


def endpoints(model: str) -> list[dict]:
    req = urllib.request.Request(
        f"https://openrouter.ai/api/v1/models/{model}/endpoints",
        headers={"Authorization": f"Bearer {key}"},
    )
    return json.loads(urllib.request.urlopen(req, timeout=30).read())["data"].get("endpoints", [])


def rank(eps: list[dict]) -> tuple[list[str], list[str], list[str]]:
    healthy, broken = [], []
    for e in eps:
        up = e.get("uptime_last_30m")
        operational = e.get("status") == 0 and (up is None or up >= UPTIME_FLOOR)
        (healthy if operational else broken).append(e)

    def p50(v):
        # latency/throughput are percentile dicts {p50,p75,p90,p99}; a scalar or None is tolerated.
        if isinstance(v, dict):
            return v.get("p50")
        return v

    def sort_key(e: dict):
        # Stability is already GATED (uptime>=floor + status==0). Among the stable set, rank by SPEED:
        # throughput p50 desc PRIMARY (our verifier calls are reasoning-heavy = long outputs, so
        # tokens/sec dominates total time), latency p50 asc secondary (time-to-first-token), uptime
        # desc final tiebreak. None metrics rank last. -> "stable (gated) AND fastest (sorted)".
        tput = p50(e.get("throughput_last_30m"))
        lat = p50(e.get("latency_last_30m"))
        up = e.get("uptime_last_30m")
        return (
            -(tput if tput is not None else -1.0),
            (lat if lat is not None else float("inf")),
            -(up if up is not None else -1.0),
        )

    def slug(e: dict) -> str:
        # OpenRouter provider.order/ignore expects the provider SLUG (the `tag` prefix before '/',
        # e.g. 'deepinfra/fp4' -> 'deepinfra'), NOT the display provider_name ('DeepInfra' / 'Io Net').
        tag = e.get("tag") or ""
        return tag.split("/")[0] if tag else (e.get("provider_name") or "").lower().replace(" ", "-")

    healthy.sort(key=sort_key)

    def dedup(eps_list: list[dict]) -> list[str]:
        # a provider may expose several quant endpoints; keep its FIRST (best-ranked) slug only.
        seen, out = set(), []
        for e in eps_list:
            s = slug(e)
            if s and s not in seen:
                seen.add(s); out.append(s)
        return out

    order = dedup(healthy)[:TOP_N]
    ignore = [s for s in dedup(broken) if s not in set(order)]
    notes = []
    if len(healthy) < 3:
        notes.append(f"THIN POOL: only {len(healthy)} healthy provider(s)")
    if any(e.get("uptime_last_30m") is None for e in healthy):
        notes.append("some providers have NULL uptime (ranked last)")
    return order, ignore, notes


def main():
    out_lines = [
        "# I-run11-007 (#1051): per-role OpenRouter provider routing — ranked HEALTHY chain.",
        "# Generated by scripts/diagnostics/rank_openrouter_providers.py from live endpoint health.",
        f"# Ranking: status==0 + uptime_last_30m>={UPTIME_FLOOR}, sorted uptime desc / latency asc / throughput desc.",
        "# Used with allow_fallbacks:false so off-list (flaky) providers are NEVER tried.",
        "# Re-generate before a demo to refresh health. LAW VI: consumed as config, never inlined.",
        "roles:",
    ]
    print(f"floor={UPTIME_FLOOR} top_n={TOP_N}\n")
    for role, model in ROLE_MODELS.items():
        try:
            eps = endpoints(model)
        except Exception as ex:  # noqa: BLE001
            print(f"{role} {model}: FETCH ERROR {str(ex)[:80]}"); continue
        order, ignore, notes = rank(eps)
        print(f"{role:10} ({model}): order={order}  ignore={ignore}  {notes}")
        out_lines += [
            f"  {role}:",
            f"    model: {model}",
            f"    order: [{', '.join(order)}]",
            f"    ignore: [{', '.join(ignore)}]",
        ]
        if notes:
            out_lines.append(f"    notes: \"{'; '.join(notes)}\"")
    os.makedirs("config/settings", exist_ok=True)
    with open("config/settings/openrouter_provider_routing.yaml", "w", encoding="utf-8") as f:
        f.write("\n".join(out_lines) + "\n")
    print("\nwrote config/settings/openrouter_provider_routing.yaml")


if __name__ == "__main__":
    main()
