#!/usr/bin/env python3
"""ATTACK 6, END TO END, WITH THE REAL LLM. Feed a judicial opinion to mine_paper() and see what
the pipeline actually does with a source that carries a holding instead of an effect size."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
sys.path.insert(0, str(ROOT))

import evidence_miner as EM
import research_contract as RC

Q = ('How is artificial intelligence changing the labour market? Review the evidence on '
     'employment, wages and job displacement across industries.')

OPINION = """SUPREME COURT OF THE UNITED STATES
No. 22-1008. Argued October 3, 2023 - Decided June 14, 2024
MOTA v. UNITED PARCEL LOGISTICS
JUSTICE KAGAN delivered the opinion of the Court.

I. BACKGROUND
Respondent United Parcel Logistics deploys an automated resume-screening system to rank applicants
for warehouse positions. Petitioner Mota, who is over forty, applied and was screened out. She sued
under Title VII, alleging disparate impact.

II. HOLDING
Held: An employer that deploys an automated screening system remains liable under Title VII for the
disparate impact of that system upon a protected class, and the employer bears the burden of proving
that the system is job-related and consistent with business necessity. The fact that the criteria
applied were generated by a machine-learning model, rather than articulated by a human decisionmaker,
does not relieve the employer of that burden. Delegation of a hiring judgment to an algorithm is not
delegation of the statutory duty that attends it.

III. REASONING
It is emphatically the province of the employer, and not of the vendor, to answer for the criteria by
which applicants are excluded. We decline to import into Title VII a safe harbour that Congress did
not enact. Where the model is opaque even to the party deploying it, that opacity is the employer's
burden and not the claimant's. An employer may not purchase immunity from the statute by purchasing
a model it does not understand.

The judgment of the Court of Appeals is reversed and the case is remanded for further proceedings.
"""

paper = {'doi': '10.x/mota', 'title': 'Mota v. United Parcel Logistics', 'authors': ['Mota'],
         'year': 2024, 'venue': 'Supreme Court of the United States', 'abstract': '',
         'attribution': 'In Mota v. United Parcel Logistics (2024), the Supreme Court',
         'attribution_short': 'Mota v. UPL (2024)', 'fulltext': OPINION,
         'content_status': 'FULLTEXT'}

mc = EM.load_contract(Q, None)
rejects = EM.new_rejects()
stats = EM.new_stats()

print('=' * 100)
print('ATTACK 6 LIVE — the REAL miner, the REAL LLM, on a judicial opinion.')
print('=' * 100)
print(f'\n  {len(OPINION.split())} words. The holding is the evidence. There is no effect size,')
print('  because a holding is not a measurement.\n')

cards = EM.mine_paper(paper, mc, use_llm=True, rejects=rejects, stats=stats)

print(f'\n  LLM calls          : {stats.get("llm_calls", "?")}')
print(f'  candidates harvested: {stats["candidates"]}   <- the deterministic recall stage')
print(f'  LLM proposed       : {stats.get("llm_proposed", 0)}')
print(f'  CARDS PRODUCED     : {len(cards)}')
print(f'  rejects            : {[(k, v) for k, v in rejects.items() if v and k != "_examples"]}')
for c in cards:
    print(f'\n    card: span={c["span"][:88]!r}')
    print(f'          effect={c.get("effect")!r} unit={c.get("unit")!r} outcome={c.get("outcome")!r}')
    print(f'          kind={c.get("card_kind")!r}')

# --- what does the coverage matrix do with whatever survived? ---
print('\n--- and what does the coverage matrix do with it? ---')
contract = RC.compile_contract(Q, None)
for c in cards:
    c.setdefault('id', 'c0')
    c.setdefault('section_weight', 1.0)
print(f'  has_verified_figure : {[RC.has_verified_figure(c) for c in cards]}')
print(f'  has_direct_result   : {[RC.has_direct_result(c) for c in cards]}')
if cards:
    m = RC.coverage_matrix(contract, cards, corpus=[])
    live = [x for x in m.cells.values() if x.card_ids]
    for x in live:
        print(f'    [{x.status}] {x.row_label[:24]} x {x.col_label[:22]}  n_works={x.n_works} '
              f'n_quant={x.n_quant} n_qual={x.n_qual}')
        print(f'         reason: {x.reason}')
    print(f'  UNROUTED: {m.unrouted}')
