#!/usr/bin/env python3
"""ATTACK 5 (properly) and ATTACK 6 (with the correct contract object)."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
sys.path.insert(0, str(ROOT))

import research_contract as RC
import evidence_miner as EM

CORPUS = json.loads((ROOT / 'outputs' / 'journal_corpus_content.json').read_text())
Q = ('How is artificial intelligence changing the labour market? Review the evidence on '
     'employment, wages and job displacement across industries.')
contract = RC.compile_contract(Q, None)

print('=' * 100)
print('ATTACK 5 (PROPER) — THE MOST ON-TOPIC SENTENCE IMAGINABLE, IN THE DIMENSION\'S OWN WORD.')
print('=' * 100)

col_m, _ = RC.build_matchers(list(contract.outcome_dimensions))
wm = col_m['wages']
print(f'\n  The `Wages` dimension matches on:')
print(f'     phrases     : {wm.phrases}')
print(f'     disc stems  : {sorted(wm.disc)}')
print(f'\n  Note what is ABSENT: the stem "wage". It is shared with `Skill premium`')
print(f'  ("wage inequality", "educational wage gap"), so document-frequency inside the family')
print(f'  DISQUALIFIED IT as discriminative. The dimension called Wages cannot match the word "wage".')


def card(cid, span, **kw):
    d = {'id': cid, 'doi': f'10.9/{cid}', 'venue': 'Econometrica', 'year': 2022,
         'authors': ['Real'], 'source': 'Real (2022), Econometrica',
         'attribution': 'Writing in Econometrica in 2022, Real', 'span': span, 'claim': 'x',
         'effect': '4.1', 'unit': 'percent', 'comparator': 'after robot adoption',
         'outcome': 'wages', 'population': 'US workers', 'geography': '', 'period': '',
         'technology': 'robots', 'industry': '', 'unit_of_analysis': 'worker',
         'design': 'observational', 'uncertainty': '', 'mechanisms': [], 'has_number': True,
         'section': 'results', 'section_weight': 1.0, 'complete_tuple': True,
         'span_start': 0, 'span_end': len(span), 'method': 'observational'}
    d.update(kw)
    return d


tests = [
    ('c1', 'We find that wages fell by 4.1 percent following the adoption of industrial robots.'),
    ('c2', 'Real wages declined 4.1 percent in exposed local labour markets.'),
    ('c3', 'The wage effect of automation was a decline of 4.1 percent.'),
]
cards = [card(cid, s) for cid, s in tests]
m = RC.coverage_matrix(contract, cards, corpus=CORPUS)

print(f'\n  THREE cards. Every one of them is a measured WAGE finding:')
for c in cards:
    print(f'     {c["id"]}: {c["span"]!r}')
print(f'\n  routed anywhere?   {[(c.row_label[:18], c.col_label) for c in m.cells.values() if c.card_ids] or "NO CELL CLAIMED ANY OF THEM"}')
print(f'  UNROUTED           : {m.unrouted}')
wage_cells = [c for c in m.cells.values() if c.col == 'wages']
print(f'\n  the WAGES column, after ingesting three wage findings:')
for c in wage_cells[:4]:
    print(f'     [{c.status}] {c.row_label[:28]:<29} n_works={c.n_works}  :: {c.reason[:58]}')

gaps = m.by_status(RC.GAP)
print(f'\n  cells GAP: {len(gaps)}/{len(m.cells)}   (ALL of them)')
print(f'\n  The report slot that reaches the page (research_contract.py:993-996):')
print(f'      title = "What the reviewed literature does not cover"')
print(f'      cells = []          # "a gap slot cites NOTHING: that is what makes it a gap"')
if m.unrouted:
    print(f'\n  >>> ATTACK 5 SUCCEEDS.')
    print(f'  >>> The corpus HOLDS three measured wage findings. The artifact will say the reviewed')
    print(f'  >>> literature DOES NOT COVER WAGES. The `unrouted` list knows better and is printed')
    print(f'  >>> only to a terminal by print_matrix() — a console diagnostic (line 1249).')
    print(f'  >>> A LEXICAL MISS AND A GENUINE ABSENCE PRODUCE THE IDENTICAL ARTIFACT.')

# =================================================================================================
print('\n' + '=' * 100)
print('ATTACK 6 (PROPER) — a doctrinal holding, through the REAL MiningContract.')
print('=' * 100)

mc = EM.load_contract(Q, None)          # <- the MiningContract gate_card actually expects

OPINION = """SUPREME COURT OF THE UNITED STATES
MOTA v. UNITED PARCEL LOGISTICS

Held: An employer that deploys an automated screening system remains liable under Title VII for the
disparate impact of that system upon a protected class, and the employer bears the burden of proving
that the system is job-related and consistent with business necessity. The fact that the criteria
applied were generated by a machine-learning model, rather than articulated by a human decisionmaker,
does not relieve the employer of that burden. Delegation of a hiring judgment to an algorithm is not
delegation of the statutory duty that attends it.

It is emphatically the province of the employer, and not of the vendor, to answer for the criteria by
which applicants are excluded. Where the model is opaque even to the party deploying it, that opacity
is the employer's burden and not the claimant's.
"""

paper = {'doi': '10.x/mota', 'title': 'Mota v. United Parcel Logistics', 'authors': ['Mota'],
         'year': 2024, 'venue': 'Supreme Court of the United States', 'abstract': '',
         'attribution': 'In Mota v. United Parcel Logistics (2024), the Supreme Court',
         'attribution_short': 'Mota v. UPL (2024)', 'fulltext': OPINION, 'content_status': 'FULLTEXT'}

# THE OPINION MUST BE IN THE GRAPH: a card is a bound span, and it binds to a MANIFESTATION.
# `type: judicial-opinion` makes the work a `case`, whose artifact is COMPLETE AT ANY LENGTH.
import provenance as P
row_op = dict(paper, type='judicial-opinion')
G = P.migrate([row_op])
MID = next(iter(G.manifestations))
paper = dict(paper, manifestation_id=MID)
print(f"\n  the opinion, in the graph: {G.manifestations[MID].profile['artifact_kind']} "
      f"(complete={G.manifestations[MID].profile['complete']}, "
      f"{G.manifestations[MID].profile['n_words']} words)")

view, chunks = EM.chunk_document('op', G.manifestations[MID].text)
cands = [c for ch in chunks for c in EM.harvest(ch, mc)]
qual = [c for c in cands if not c['quantitative']]
print(f'\n  1. harvest() — the deterministic recall stage — candidates found: {len(cands)}'
      f'  ({len(qual)} qualitative)')
print(f'     the no-digit discard (`if not re.search(r"\\d", t): continue`) IS GONE.')
print(f'     families seen: {sorted({f for c in cands for f in c["families"]})}')

holding = ('the employer bears the burden of proving that the system is job-related and consistent '
           'with business necessity')
pw = EM.paper_window(view, chunks, paper)
ch0 = next((c for c in chunks if holding[:40] in c.text), chunks[0])

print(f'\n  2. Now HAND the holding to gate_card() as if a model had proposed it anyway.')
for label, raw in [
    ('the holding, TYPED as what it is (doctrinal_holding_or_rule)',
     dict(act='doctrinal_holding_or_rule', span=holding,
          holding='the employer bears the burden of proving that the system is job-related and '
                  'consistent with business necessity',
          authority='the employer', mechanisms=[])),
    ('the OLD shape: an untyped card with no effect/unit/outcome (what the gate used to destroy)',
     dict(span=holding, effect='', unit='', comparator='', outcome='', population='', geography='',
          period='', technology='', industry='', unit_of_analysis='', design='', uncertainty='',
          horizon='', mechanisms=[])),
]:
    rej = EM.new_rejects()
    c = EM.gate_card(raw, view, ch0, paper, pw, mc, rej,
                     graph=G, source_policy=P.OFFICIAL_TEXT)
    fired = [(k, v) for k, v in rej.items() if v and not k.startswith('_')]
    print(f'\n     {label}')
    print(f'       -> {"REJECTED" if c is None else "ADMITTED as a card"}   rejects={fired}')
    if c:
        print(f'          act        : {c["act"]}')
        print(f'          claim      : {c["claim"][:88]}')
        print(f'          attribution: {c["attribution"]}')
        print(f'          bound to   : {c["manifestation_id"]} / {c["content_hash"][:16]}...')
        print(f'\n     >>> ATTACK 6 IS DEAD. A judicial opinion produces evidence.')

print(f'\n  3. THE PROMPT the model is now given (evidence_miner.mine_prompt(), from the REGISTRY):')
print(f'       "You are mining a source document for EVIDENCE... Each act is one thing the source')
print(f'        DOES with evidence, and it is TYPED."')
for a in EM.REGISTRY.acts.values():
    req = ' + '.join(a.required_all) or '-'
    print(f'         {a.id:<30} required: {req}')
print(f'     The registry is DATA (config/evidence_acts.json, {EM.REGISTRY.version}). Adding an act')
print(f'     type to a corpus of case law is a data edit, not a code edit.')

print(f'\n  4. research_contract._close() needs >=1 quantitative OR "direct qualitative" result;')
print(f'     has_direct_result() requires a RESULT VERB in the span:')
print(f'       _RESULT_VERB matches the holding? {bool(RC._RESULT_VERB.search(holding))}')

print(f'\n  >>> ATTACK 6 IS DEAD:')
print(f'  >>>   RECALL  — harvest() no longer requires a digit; the holding IS a candidate, typed.')
print(f'  >>>   PROMPT  — the model is asked for TYPED ACTS, and doctrinal_holding_or_rule is one.')
print(f'  >>>   SCHEMA  — the act declares `holding` + `authority`; it needs no effect and no outcome.')
print(f'  >>>   COUNTING— every rejection has a counter (act_missing_required:<act>), every block')
print(f'  >>>             examined is counted (blocks_examined / blocks_no_act). A discard can no')
print(f'  >>>             longer read as an empty document.')
print(f'  >>> AND D1 DID NOT MOVE: the quantitative candidate set is bit-identical (620 = 620 on the')
print(f'  >>> live corpus), and the qualitative lane has its own reserved slots in the prompt.')
