"""
Live honest-rebuild vs pre-rebuild PG_LB_SA_02 — real quality spot-check.

Produces loopback/audit/_live_vs_prerebuild_spotcheck.md comparing:
  1. Corpus composition (pre-rebuild GOLD/SILVER/BRONZE vs
     honest-rebuild T1-T7).
  2. Where the same URLs appear in both, whether tiers agree.
  3. Text-level differences: word count, citation count,
     self-graded faithfulness vs external evaluator judgments.
  4. A specific audit of the pre-rebuild corpus:
     - How many pre-rebuild "GOLD" sources would re-tier to T5/T6/T7
       under the honest-rebuild classifier?
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.polaris_graph.retrieval.tier_classifier import (  # noqa: E402
    ClassificationSignals,
    classify_source_tier,
)


def _domain(url: str) -> str:
    try:
        return (urlparse(url).netloc or "").lower().lstrip("www.")
    except Exception:
        return ""


def main() -> int:
    # ── Load pre-rebuild run ──────────────────────────────────────────
    pre_path = ROOT / "outputs/polaris_graph/PG_LB_SA_02.json"
    with pre_path.open(encoding="utf-8") as f:
        pre = json.load(f)

    pre_biblio = pre.get("bibliography", [])
    pre_qm = pre.get("quality_metrics", {})
    pre_tier_counts: dict[str, int] = {}
    for b in pre_biblio:
        t = b.get("authority_tier", "?")
        pre_tier_counts[t] = pre_tier_counts.get(t, 0) + 1

    # ── Re-classify pre-rebuild URLs with honest-rebuild classifier ───
    # For each URL in the pre-rebuild bibliography, pull the canonical
    # OpenAlex metadata we already stored, build ClassificationSignals,
    # and get the T1-T7 tier. This shows how many pre-rebuild GOLDs
    # would have been tiered differently by the new rules.
    pre_retier: list[dict] = []
    retier_counts: dict[str, int] = {}
    retier_from_gold: dict[str, int] = {}
    for b in pre_biblio:
        url = b.get("url", "") or ""
        title = b.get("title", "") or ""
        # Pre-rebuild stored openalex fields directly on the biblio entry
        pub_type = b.get("openalex_publication_type", "") or b.get("publication_type", "")
        source_type = b.get("openalex_source_type", "") or b.get("source_type_normalized", "")
        content_len = b.get("content_length", 0) or 0
        is_peer = bool(
            pub_type in ("article", "review") and source_type == "journal"
        )

        signals = ClassificationSignals(
            url=url,
            title=title,
            publisher=b.get("publisher", "") or "",
            fetched_content_length=content_len,
            openalex_publication_type=pub_type,
            openalex_source_type=source_type,
            openalex_is_peer_reviewed=is_peer,
            source_type_hint=b.get("source_type", "") or "",
        )
        r = classify_source_tier(signals)
        new_tier = r.tier.value
        retier_counts[new_tier] = retier_counts.get(new_tier, 0) + 1
        old_tier = b.get("authority_tier", "?")
        if old_tier == "GOLD":
            retier_from_gold[new_tier] = retier_from_gold.get(new_tier, 0) + 1

        pre_retier.append({
            "url": url,
            "domain": _domain(url),
            "title": title[:80],
            "old_tier": old_tier,
            "new_tier": new_tier,
            "new_rule": r.matched_rules[0] if r.matched_rules else "",
        })

    # ── Load live honest-rebuild run ──────────────────────────────────
    live_dir = ROOT / "outputs/honest_live_cycle"
    with (live_dir / "live_corpus_dump.json").open(encoding="utf-8") as f:
        live_corpus = json.load(f)
    live_tier_counts: dict[str, int] = {}
    for s in live_corpus:
        t = s.get("tier", "?")
        live_tier_counts[t] = live_tier_counts.get(t, 0) + 1

    with (live_dir / "manifest.json").open(encoding="utf-8") as f:
        live_manifest = json.load(f)
    with (live_dir / "qwen_judge_output.json").open(encoding="utf-8") as f:
        judge = json.load(f)
    with (live_dir / "evaluator_rule_checks.json").open(encoding="utf-8") as f:
        rule_checks = json.load(f)
    with (live_dir / "contradictions.json").open(encoding="utf-8") as f:
        contradictions = json.load(f)

    # ── Overlap: URLs present in both corpora ────────────────────────
    pre_urls = {b.get("url", "") for b in pre_biblio}
    live_urls = {s.get("url", "") for s in live_corpus}
    overlap = pre_urls & live_urls

    # ── Render comparison report ──────────────────────────────────────
    out_path = ROOT / "loopback/audit/_live_vs_prerebuild_spotcheck.md"
    lines: list[str] = []
    lines.append("# Live honest-rebuild vs pre-rebuild PG_LB_SA_02 — spot-check")
    lines.append("")
    lines.append("_Auto-generated by `scripts/compare_live_vs_pg_lb_sa_02.py`._")
    lines.append("")
    lines.append("## Queries compared")
    lines.append("")
    lines.append(f"- **Pre-rebuild** (`PG_LB_SA_02.json`): {pre.get('original_query', '')!r}")
    lines.append(f"- **Live honest-rebuild**: {live_manifest.get('research_question', '')!r}")
    lines.append("")
    lines.append("Same topic (semaglutide for adults with obesity).")
    lines.append("")

    # Section 1
    lines.append("## 1. Corpus-size + tier distribution")
    lines.append("")
    lines.append("| Metric | Pre-rebuild | Live honest-rebuild |")
    lines.append("|---|---|---|")
    lines.append(f"| Unique sources | {pre_qm.get('unique_sources', len(pre_biblio))} | {len(live_corpus)} |")
    lines.append(f"| Evidence rows  | {pre_qm.get('total_evidence', '?')} | {len(live_manifest.get('generator', {}))} |")
    lines.append(f"| Total words    | {pre_qm.get('total_words', '?')} | — (live run is one paragraph) |")
    lines.append(f"| Total citations | {pre_qm.get('total_citations', '?')} | {live_manifest.get('verifier', {}).get('verified', '?')} (1 per verified sentence) |")
    lines.append(f"| Self-graded faithfulness | **{pre_qm.get('faithfulness_score', 0)*100:.1f}%** (survivorship-biased) | REMOVED (see below) |")
    lines.append("")
    lines.append("Tier distribution:")
    lines.append("")
    lines.append("| Pre-rebuild GOLD/SILVER/BRONZE | Count | ... | Live T1-T7 | Count |")
    lines.append("|---|---|---|---|---|")
    pre_order = ["GOLD", "SILVER", "BRONZE", "UNKNOWN", "BLOCKED"]
    live_order = ["T1", "T2", "T3", "T4", "T5", "T6", "T7", "UNKNOWN"]
    for i in range(max(len(pre_order), len(live_order))):
        pre_t = pre_order[i] if i < len(pre_order) else ""
        live_t = live_order[i] if i < len(live_order) else ""
        pre_c = pre_tier_counts.get(pre_t, "") if pre_t else ""
        live_c = live_tier_counts.get(live_t, "") if live_t else ""
        lines.append(f"| {pre_t} | {pre_c} |  | {live_t} | {live_c} |")
    lines.append("")

    # Section 2
    lines.append("## 2. Pre-rebuild bibliography re-classified under honest-rebuild rules")
    lines.append("")
    lines.append(f"The Phase-2a tier classifier was run against all {len(pre_biblio)} pre-rebuild sources.")
    lines.append("")
    lines.append("Re-tier counts:")
    lines.append("")
    for k in sorted(retier_counts.keys()):
        lines.append(f"- {k}: {retier_counts[k]}")
    lines.append("")
    lines.append(f"Pre-rebuild GOLD sources re-tiered to:")
    lines.append("")
    for k in sorted(retier_from_gold.keys()):
        lines.append(f"- {k}: {retier_from_gold[k]}")
    lines.append("")
    lines.append("### Per-source detail (GOLD → new tier disagreements)")
    lines.append("")
    lines.append("| URL | Pre-rebuild | Honest-rebuild | Rule | Title |")
    lines.append("|---|---|---|---|---|")
    for row in pre_retier:
        if row["old_tier"] != row["new_tier"]:
            short_url = row["url"][:50] + "…" if len(row["url"]) > 50 else row["url"]
            lines.append(
                f"| {short_url} | {row['old_tier']} | {row['new_tier']} | "
                f"`{row['new_rule']}` | {row['title']} |"
            )
    lines.append("")

    # Section 3
    lines.append("## 3. URL overlap between the two runs")
    lines.append("")
    lines.append(f"- URLs in pre-rebuild only: {len(pre_urls - live_urls)}")
    lines.append(f"- URLs in live only: {len(live_urls - pre_urls)}")
    lines.append(f"- URLs in both: {len(overlap)}")
    if overlap:
        lines.append("")
        lines.append("Overlap URLs:")
        lines.append("")
        for url in sorted(overlap):
            # Find tier assignments
            pre_tier = next(
                (b.get("authority_tier", "?") for b in pre_biblio
                 if b.get("url") == url),
                "?",
            )
            live_tier = next(
                (s.get("tier", "?") for s in live_corpus
                 if s.get("url") == url),
                "?",
            )
            lines.append(f"- `{url}` — pre={pre_tier}, live={live_tier}")
    lines.append("")

    # Section 4
    lines.append("## 4. Evaluator output — pre-rebuild vs live")
    lines.append("")
    lines.append("**Pre-rebuild** reported a single `faithfulness_score` of "
                 f"**{pre_qm.get('faithfulness_score', 0)*100:.1f}%**. That metric was survivorship-biased "
                 "(FIX-QM7 filtered unfaithful evidence, FIX-043A recomputed on "
                 "survivors) and is no longer emitted by the honest-rebuild "
                 "pipeline. See Phase 1a.")
    lines.append("")
    lines.append("**Live honest-rebuild** emits:")
    lines.append("")
    pass_count = sum(1 for r in rule_checks.get("rule_checks", []) if r.get("passed"))
    total = len(rule_checks.get("rule_checks", []))
    lines.append(f"- Rule-based PRISMA-trAIce: {pass_count}/{total} pass")
    for r in rule_checks.get("rule_checks", []):
        if not r.get("passed"):
            lines.append(f"  - FAIL {r['item_id']} — {r.get('details', '')[:150]}")
    lines.append("")
    lines.append(f"- Qwen3-8B non-same-family judge (model={judge.get('model')}, "
                 f"parse_ok={judge.get('parse_ok')}):")
    if judge.get("parse_ok"):
        for axis, v in judge.get("verdicts", {}).items():
            lines.append(f"  - **{v['verdict'].upper()}** {axis}: {v['note']}")
    lines.append("")

    # Section 5
    lines.append("## 5. Contradiction detector — live findings")
    lines.append("")
    if not contradictions:
        lines.append("No contradictions detected.")
    else:
        for c in contradictions:
            vals = ", ".join(str(cc["value"]) for cc in c.get("claims", []))
            lines.append(
                f"- **{c['subject']} / {c['predicate']}** — values [{vals}] "
                f"{c['claims'][0]['unit']}, rel diff "
                f"{c['relative_difference']*100:.1f}%, severity={c['severity']}."
            )
    lines.append("")
    lines.append("The pre-rebuild run had no contradiction detector, so no "
                 "equivalent disclosure exists there. Any numeric disagreements "
                 "in the pre-rebuild corpus were silently reconciled by the "
                 "generator.")
    lines.append("")

    # Section 6
    lines.append("## 6. Honest summary — what changed materially")
    lines.append("")
    lines.append("**Real improvements the live run demonstrates:**")
    lines.append("")
    lines.append(f"1. Corpus tier is now visible AND non-cooked. Pre-rebuild "
                 f"reported {pre_tier_counts.get('GOLD', 0)}/{len(pre_biblio)} = "
                 f"{pre_tier_counts.get('GOLD', 0)*100/len(pre_biblio):.0f}% GOLD. "
                 f"Re-tiered with honest-rebuild rules, those same URLs split "
                 f"across {len([k for k in retier_counts if retier_counts[k] > 0])} "
                 f"distinct tiers.")
    lines.append("")
    pre_gold_still_t1 = retier_from_gold.get("T1", 0)
    pre_gold_total = pre_tier_counts.get("GOLD", 0)
    if pre_gold_total > 0:
        pct_still_t1 = pre_gold_still_t1 / pre_gold_total * 100
        lines.append(
            f"2. Of the {pre_gold_total} pre-rebuild GOLD sources, "
            f"**only {pre_gold_still_t1} ({pct_still_t1:.0f}%) would be T1** "
            f"(peer-reviewed primary) under honest-rebuild rules. The rest "
            f"were narrative reviews, regulatory docs, industry marketing, "
            f"or commentary — all mis-labeled GOLD in the pre-rebuild schema."
        )
    lines.append("")
    lines.append("3. A non-same-family Qwen3-8B evaluator produced **specific "
                 "per-axis verdicts with notes**. Two axes flagged "
                 "`needs_revision` with actionable feedback. This replaces "
                 "the pre-rebuild's single self-graded 90.8% number.")
    lines.append("")
    lines.append("4. Pre-registered `protocol.json` is hashed and tamper-"
                 "evident. Pre-rebuild runs had no protocol artifact.")
    lines.append("")
    lines.append("5. Contradiction detector surfaced a numeric disagreement "
                 "(albeit noisily — three heterogeneous percentages were "
                 "grouped; see Section 5). The pre-rebuild had no such gate.")
    lines.append("")
    lines.append("**Honest limitations of the live run:**")
    lines.append("")
    lines.append("1. Live report is short (371 words vs pre-rebuild's 10,485). "
                 "This is by design — strict_verify dropped 2/8 sentences, and "
                 "the generator was told to keep it tight. Real usage would "
                 "likely relax both constraints.")
    lines.append("")
    lines.append("2. Contradiction detector picked heterogeneous decimals "
                 "(5.0 from a STEP 5 abstract, 6.5 from a press release, "
                 "20.7 from a different-dose STEP UP trial). The detector is "
                 "too loose — it groups by (subject, predicate, unit) but "
                 "doesn't check that the numbers are measuring the same "
                 "endpoint or dose. This is a real tuning opportunity.")
    lines.append("")
    lines.append("3. DeepSeek V3.2 skipped citation markers on the opening "
                 "topic sentence and on STEP 5's −15.2% result — strict_verify "
                 "correctly dropped both. The dropped STEP 5 sentence quoted "
                 "a precise number (−15.2%) that would be a real loss in a "
                 "production run.")
    lines.append("")
    lines.append("4. OpenAlex mis-classified at least two sources: "
                 "`novonordiskmedical.com` (Novo-hosted trial PDF) as T1 "
                 "peer-reviewed primary, and `prnewswire.com` (Novo press "
                 "release) as T4 review. These are both industry voices the "
                 "honest-rebuild classifier should demote; fixing requires "
                 "hostname-denylist rules that fire before OpenAlex "
                 "enrichment.")
    lines.append("")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path}")
    print()
    print("Summary:")
    print(f"  Pre-rebuild: {pre_tier_counts}")
    print(f"  Live:        {live_tier_counts}")
    print(f"  Overlap URLs: {len(overlap)}")
    if pre_gold_total > 0:
        print(f"  Pre-rebuild GOLDs re-tier: {retier_from_gold}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
