"""
Apples-to-apples: run the honest-rebuild generator + evaluator on the
EXACT same URL + evidence set that PG_LB_SA_02 used.

This bypasses retrieval entirely. The goal is to answer: "if we give
both pipelines the same corpus, does the honest-rebuild output show
measurably different behavior?"

Inputs:
  outputs/polaris_graph/PG_LB_SA_02.json  (pre-rebuild run artifact)

Outputs:
  outputs/honest_on_prerebuild_corpus/
    protocol.json
    live_corpus_dump.json
    corpus_approval.json
    contradictions.json
    report.md                (generated by DeepSeek V3.2-Exp + strict_verify)
    evaluator_rule_checks.json
    judge_output.json
    manifest.json
    run_log.txt
    side_by_side.md          (honest-rebuild report vs pre-rebuild report)
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
import time
from dataclasses import asdict
from pathlib import Path

from dotenv import load_dotenv
load_dotenv(override=False)

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

logging.basicConfig(
    level=os.environ.get("PG_LOG_LEVEL", "INFO"),
    format="%(asctime)s %(name)s %(levelname)s %(message)s",
    datefmt="%H:%M:%S",
    stream=sys.stdout,
)
for noisy in ("httpx", "httpcore"):
    logging.getLogger(noisy).setLevel(logging.WARNING)

from src.polaris_graph.evaluator.external_evaluator import run_external_evaluation  # noqa: E402
from src.polaris_graph.evaluator.live_judge import judge_report  # noqa: E402
from src.polaris_graph.generator.live_deepseek_generator import generate_live_draft  # noqa: E402
from src.polaris_graph.generator.multi_section_generator import (  # noqa: E402
    generate_multi_section_report,
)
from src.polaris_graph.generator.provenance_generator import (  # noqa: E402
    resolve_provenance_to_citations,
    strict_verify,
)
from src.polaris_graph.nodes.corpus_approval_gate import (  # noqa: E402
    CorpusApprovalDecision, CorpusSource,
    check_auto_approve_allowed, compute_tier_distribution,
    save_approval_decision,
)
from src.polaris_graph.nodes.scope_gate import run_scope_gate  # noqa: E402
from src.polaris_graph.retrieval.contradiction_detector import (  # noqa: E402
    detect_contradictions,
    extract_numeric_claims,
)
from src.polaris_graph.retrieval.tier_classifier import (  # noqa: E402
    ClassificationSignals,
    classify_source_tier,
)


def _domain_of(url: str) -> str:
    from urllib.parse import urlparse
    try:
        return (urlparse(url).netloc or "").lower().lstrip("www.")
    except Exception:
        return ""


def _normalize_url(url: str) -> str:
    """Gap-1 fix: URL variants between bibliography and evidence rows were
    causing url_to_tier misses (trailing slash, www prefix, fragments,
    case). Normalize for stable lookup."""
    from urllib.parse import urlparse, urlunparse
    if not url:
        return ""
    try:
        p = urlparse(url.strip())
        scheme = (p.scheme or "https").lower()
        netloc = (p.netloc or "").lower()
        if netloc.startswith("www."):
            netloc = netloc[4:]
        path = (p.path or "").rstrip("/")
        # Drop fragment; keep query (query carries real info like
        # ?doi=... in jomes.org URLs).
        return urlunparse((scheme, netloc, path, p.params, p.query, ""))
    except Exception:
        return url.strip().lower().rstrip("/")


def _build_honest_rebuild_evidence(pre: dict) -> tuple[list[CorpusSource], list[dict]]:
    """Re-classify pre-rebuild bibliography under honest-rebuild rules,
    and build an evidence_rows list from pre-rebuild evidence rows."""
    classified: list[CorpusSource] = []
    url_to_tier: dict[str, str] = {}

    for b in pre.get("bibliography", []):
        url = b.get("url", "") or ""
        title = b.get("title", "") or ""
        pub_type = b.get("publication_type", "") or ""
        source_type = b.get("source_type_normalized", "") or ""
        content_len = 10000  # pre-rebuild doesn't store this per-source
        is_peer = bool(
            pub_type in ("article", "review") and source_type == "journal"
        )
        sig = ClassificationSignals(
            url=url,
            title=title,
            publisher="",
            fetched_content_length=content_len,
            openalex_publication_type=pub_type,
            openalex_source_type=source_type,
            openalex_is_peer_reviewed=is_peer,
            source_type_hint=b.get("source_type", "") or "",
        )
        r = classify_source_tier(sig)
        classified.append(CorpusSource(
            url=url, title=title, domain=_domain_of(url),
            tier=r.tier.value, tier_confidence=r.confidence,
            tier_rule=r.matched_rules[0] if r.matched_rules else "",
            tier_reasons=list(r.reasons),
        ))
        # Gap-1 fix: key url_to_tier by normalized URL so evidence-row
        # URLs (with www./slash/fragment variants) still find their tier.
        url_to_tier[_normalize_url(url)] = r.tier.value

    # Collect evidence rows — re-key to simple ev_NNN IDs so the
    # generator + verifier see clean tokens. Keep back-references.
    evidence_rows: list[dict] = []
    # Cap evidence count so prompt stays within budget
    max_evidence = int(os.getenv("PG_LIVE_MAX_EV_TO_GEN", "20"))
    for i, ev in enumerate(pre.get("evidence", [])[:max_evidence]):
        quote = ev.get("direct_quote", "") or ""
        statement = ev.get("statement", "") or ""
        if not (quote or statement):
            continue
        url = ev.get("source_url", "") or ""
        tier = url_to_tier.get(_normalize_url(url), "UNKNOWN")
        evidence_rows.append({
            "evidence_id": f"ev_{i:03d}",
            "source_url": url,
            "statement": statement[:300],
            "direct_quote": quote[:2000],
            "tier": tier,
            "source": "prerebuild",
            "original_evidence_id": ev.get("evidence_id", ""),
        })

    return classified, evidence_rows


async def main_async() -> int:
    pre_path = ROOT / "outputs/polaris_graph/PG_LB_SA_02.json"
    with pre_path.open(encoding="utf-8") as f:
        pre = json.load(f)

    run_dir = ROOT / "outputs" / "honest_on_prerebuild_corpus"
    run_dir.mkdir(parents=True, exist_ok=True)
    run_id = f"APPLES_{int(time.time())}"

    log_path = run_dir / "run_log.txt"
    log_f = log_path.open("w", encoding="utf-8")

    def _log(msg: str) -> None:
        print(msg)
        log_f.write(msg + "\n")
        log_f.flush()

    # R-2: reset the shared run-cost counter so the per-run cap applies
    # to THIS run only. PG_MAX_COST_PER_RUN (default $0.10) will abort
    # further LLM calls if exceeded.
    from src.polaris_graph.llm.openrouter_client import (
        current_run_cost, reset_run_cost, PG_MAX_COST_PER_RUN,
    )
    reset_run_cost()

    question = pre.get("original_query", "").strip()
    _log("=" * 72)
    _log(f"APPLES-TO-APPLES run_id={run_id}")
    _log("=" * 72)
    _log(f"Using pre-rebuild corpus from {pre_path}")
    _log(f"Pre-rebuild query (verbatim): {question!r}")
    _log(f"Budget cap (PG_MAX_COST_PER_RUN): ${PG_MAX_COST_PER_RUN:.4f}")
    _log("")

    # Phase 2b scope gate
    scope = run_scope_gate(
        research_question=question,
        run_dir=run_dir,
        run_id=run_id,
        domain="clinical",
    )
    protocol_dict = scope.protocol.to_json_dict()
    _log(f"[1/6] scope_gate: protocol sha256={scope.protocol_sha256[:16]}...")

    # Re-classify pre-rebuild corpus under honest-rebuild rules
    classified, evidence_rows = _build_honest_rebuild_evidence(pre)
    _log(f"[2/6] Re-classified {len(classified)} pre-rebuild sources")
    tier_counts: dict[str, int] = {}
    for s in classified:
        tier_counts[s.tier] = tier_counts.get(s.tier, 0) + 1
    for k in sorted(tier_counts.keys()):
        _log(f"       {k}: {tier_counts[k]}")

    (run_dir / "live_corpus_dump.json").write_text(
        json.dumps([asdict(s) for s in classified], indent=2, sort_keys=True, default=str) + "\n",
        encoding="utf-8",
    )

    # Corpus approval gate
    dist = compute_tier_distribution(classified, protocol_dict)
    approval_note = (
        "Apples-to-apples run on the PG_LB_SA_02 corpus. Deviations "
        "from the clinical template are expected because the pre-rebuild "
        "retrieval pulled a broader mix."
    )
    if dist.has_material_deviation:
        ok, _ = check_auto_approve_allowed(dist, approval_note)
        approved = ok
    else:
        approved = True
    decision = CorpusApprovalDecision(
        run_id=run_id,
        decision_at_unix=time.time(),
        decision_at_iso=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        approved=approved,
        user_note=approval_note,
        approved_source_urls=[s.url for s in classified] if approved else [],
        rejected_source_urls=[] if approved else [s.url for s in classified],
        report=dist,
        protocol_sha256=scope.protocol_sha256,
    )
    save_approval_decision(decision, run_dir)
    _log(f"[3/6] corpus_approval: approved={approved}, "
         f"material_deviation={dist.has_material_deviation}")

    # Contradiction detection
    numeric_claims = extract_numeric_claims(evidence_rows)
    contradictions = detect_contradictions(numeric_claims)
    (run_dir / "contradictions.json").write_text(
        json.dumps([asdict(c) for c in contradictions], indent=2, sort_keys=True, default=str) + "\n",
        encoding="utf-8",
    )
    _log(f"[4/6] contradictions: {len(numeric_claims)} claims extracted, "
         f"{len(contradictions)} contradictions flagged")
    for c in contradictions:
        _log(f"       - {c.subject}/{c.predicate} rel={c.relative_difference*100:.1f}% "
             f"severity={c.severity}")

    # Multi-section generation (Gap-4)
    _log(f"[5/6] DeepSeek multi-section generation (evidence={len(evidence_rows)})...")
    t0 = time.time()
    ev_pool = {ev["evidence_id"]: ev for ev in evidence_rows}
    multi = await generate_multi_section_report(
        research_question=question,
        evidence=evidence_rows,
        section_temperature=0.3,
        # M-31/M-33 (2026-04-21): match upstream defaults (2500/2400)
        # to avoid JSON truncation and section output capping. Same
        # regression class fixed in run_honest_sweep_r3.py.
        outline_max_tokens=2500,
        section_max_tokens=2400,
        min_kept_fraction=0.4,
        max_parallel_sections=3,
        # R-1: pipeline telemetry for Limitations synthesis
        tier_fractions=dist.tier_fractions,
        contradictions=[asdict(c) for c in contradictions],
        date_range=(
            protocol_dict.get("date_range")
            if isinstance(protocol_dict.get("date_range"), dict)
            else None
        ),
    )
    dt = time.time() - t0
    _log(f"       elapsed={dt:.1f}s  outline={len(multi.outline)} sections, "
         f"words={multi.total_words}, "
         f"verified={multi.total_sentences_verified}, "
         f"dropped={multi.total_sentences_dropped}")
    _log(f"       input_tok={multi.total_input_tokens} "
         f"output_tok={multi.total_output_tokens}")
    for sr in multi.sections:
        mark = "OK" if not sr.dropped_due_to_failure else "DROPPED"
        _log(f"         [{mark}] {sr.title} — verified={sr.sentences_verified} "
             f"dropped={sr.sentences_dropped} "
             f"regen={sr.regen_attempted} "
             f"focus={sr.focus[:60]!r}")
    # Persist per-section artifacts
    (run_dir / "multi_section_outline.json").write_text(
        json.dumps(
            [{"title": p.title, "focus": p.focus, "ev_ids": p.ev_ids}
             for p in multi.outline],
            indent=2, sort_keys=True,
        ) + "\n",
        encoding="utf-8",
    )
    for i, sr in enumerate(multi.sections, 1):
        (run_dir / f"section_{i:02d}_{sr.title.replace(' ', '_')}.md").write_text(
            f"# {sr.title}\n\n"
            f"Focus: {sr.focus}\n\n"
            f"## Raw draft\n{sr.raw_draft}\n\n"
            f"## Rewritten draft\n{sr.rewritten_draft}\n\n"
            f"## Verified text (global biblio remapped)\n{sr.verified_text}\n",
            encoding="utf-8",
        )

    # Assemble section prose
    section_bodies: list[str] = []
    for sr in multi.sections:
        if sr.dropped_due_to_failure or not sr.verified_text:
            continue
        section_bodies.append(f"### {sr.title}\n\n{sr.verified_text}")
    sections_concat = "\n\n".join(section_bodies)

    # R-1: add the Limitations paragraph (if generated) after sections,
    # before Methods.
    if multi.limitations_text:
        sections_concat += f"\n\n### Limitations\n\n{multi.limitations_text}"
        _log(f"       limitations: +{multi.limitations_output_tokens} tokens, "
             f"{len(multi.limitations_text.split())} words")

    biblio = multi.bibliography

    from src.polaris_graph.llm.openrouter_client import (
        PG_EVALUATOR_MODEL, PG_GENERATOR_MODEL,
    )
    tier_summary = ", ".join(
        f"{k}={v*100:.0f}%" for k, v in sorted(dist.tier_fractions.items())
    )
    methods = (
        "\n\n## Methods\n"
        f"Pre-registered protocol.json (SHA-256 {scope.protocol_sha256[:16]}...).\n"
        f"Corpus: PG_LB_SA_02 pre-rebuild retrieval (apples-to-apples).\n"
        f"Generator model: {PG_GENERATOR_MODEL} (multi-section pipeline: "
        f"outline + {len([s for s in multi.sections if not s.dropped_due_to_failure])} "
        f"parallel sections + strict_verify + regen-on-failure).\n"
        f"Evaluator model: {PG_EVALUATOR_MODEL} (different family).\n"
        f"Sources classified using T1-T7 tier taxonomy.\n"
        f"Inclusion / exclusion per clinical template. Sponsor / "
        f"conflict-of-interest review per source.\n"
        f"Prompt-injection sanitization enabled. "
        f"Retrieved {time.strftime('%Y-%m-%d')} (honest-rebuild re-tier run).\n"
        f"Expected tier distribution: T1 30-60%, T2 15-40%, T3 5-25%. "
        f"Actual: {tier_summary}.\n"
    )
    if contradictions:
        n = len(contradictions)
        pl = "contradiction" if n == 1 else "contradictions"
        methods += f"\n## Contradiction disclosures\n{n} {pl} detected:\n\n"
        for c in contradictions:
            vals = ", ".join(str(cc.value) for cc in c.claims)
            methods += (
                f"- {c.subject} / {c.predicate}: values [{vals}] "
                f"{c.claims[0].unit}, rel diff {c.relative_difference*100:.1f}%.\n"
            )
    biblio_section = "\n\n## Bibliography\n"
    for b in biblio:
        biblio_section += f"[{b['num']}] {b['statement'][:200]} — {b['url']} (tier {b['tier']})\n"
    final_report = (
        f"# Research report: {question}\n\n"
        + sections_concat + methods + biblio_section
    )
    (run_dir / "report.md").write_text(final_report, encoding="utf-8")
    (run_dir / "bibliography.json").write_text(
        json.dumps(biblio, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    _log(f"       final report: {len(final_report)} chars, {len(final_report.split())} words")

    # Phase 5 evaluator
    _log(f"[6/6] evaluator + judge")
    ev_out = run_external_evaluation(
        report_text=final_report,
        protocol=protocol_dict,
        tier_distribution_report=asdict(dist),
        contradictions=[asdict(c) for c in contradictions],
        evidence_pool=ev_pool,
        enable_llm_judge=False,
    )
    (run_dir / "evaluator_rule_checks.json").write_text(
        json.dumps(ev_out.to_json_dict(), indent=2, sort_keys=True, default=str) + "\n",
        encoding="utf-8",
    )
    _log(f"       rule checks: {ev_out.rule_check_pass_count}/12 pass")
    for r in ev_out.rule_checks:
        mark = "PASS" if r.passed else "FAIL"
        detail = f" {r.details[:80]}" if not r.passed else ""
        _log(f"         [{mark}] {r.item_id} {r.name}{detail}")

    try:
        jr = await judge_report(
            report_text=final_report,
            research_question=question,
            temperature=0.2,
            max_tokens=800,
        )
        _log(f"       Judge: parse_ok={jr.parse_ok} "
             f"input_tok={jr.input_tokens} output_tok={jr.output_tokens}")
        if jr.parse_ok:
            for axis, v in jr.verdicts.items():
                _log(f"         [{v['verdict'].upper():>15}] {axis}: {v['note'][:90]}")
        (run_dir / "judge_output.json").write_text(
            json.dumps({
                "model": jr.model, "parse_ok": jr.parse_ok,
                "verdicts": jr.verdicts, "raw_response": jr.raw_response,
                "input_tokens": jr.input_tokens, "output_tokens": jr.output_tokens,
            }, indent=2, sort_keys=True, default=str) + "\n",
            encoding="utf-8",
        )
    except Exception as exc:
        _log(f"       Judge FAILED: {exc}")
        jr = None

    # ── Side-by-side comparison ────────────────────────────────────────
    _log("")
    _log("Writing side_by_side.md...")
    pre_report_path = ROOT / "outputs/polaris_graph/PG_LB_SA_02_report.md"
    pre_report_text = pre_report_path.read_text(encoding="utf-8") if pre_report_path.exists() else ""
    pre_qm = pre.get("quality_metrics", {})

    sbs_lines = [
        "# Apples-to-apples spot-check",
        "",
        "_Honest-rebuild generator + evaluator run on the **same corpus** "
        "(URLs + evidence rows) as PG_LB_SA_02._",
        "",
        f"- **Query (both runs):** {question!r}",
        f"- **Corpus size:** {len(classified)} URLs / {len(evidence_rows)} evidence rows.",
        "",
        "## Summary table",
        "",
        "| Metric | Pre-rebuild | Honest-rebuild |",
        "|---|---|---|",
        f"| Report words  | {pre_qm.get('total_words', '?')} | {len(final_report.split())} |",
        f"| Sections      | {pre_qm.get('total_sections', '?')} | {len([s for s in multi.sections if not s.dropped_due_to_failure])} (outline-driven) + methods + biblio |",
        f"| Citations     | {pre_qm.get('total_citations', '?')} | {len(biblio)} |",
        f"| Self-graded faithfulness | **{pre_qm.get('faithfulness_score', 0)*100:.1f}%** (cooked) | REMOVED |",
        f"| Rule-check pass | N/A | {ev_out.rule_check_pass_count}/12 |",
        f"| Contradiction disclosures | 0 | {len(contradictions)} |",
        "",
        "## Pre-rebuild report (first 40 lines)",
        "",
        "```markdown",
    ]
    sbs_lines.extend(pre_report_text.splitlines()[:40])
    sbs_lines.append("```")
    sbs_lines.append("")
    sbs_lines.append("## Honest-rebuild report (full)")
    sbs_lines.append("")
    sbs_lines.append("```markdown")
    sbs_lines.extend(final_report.splitlines())
    sbs_lines.append("```")
    (run_dir / "side_by_side.md").write_text("\n".join(sbs_lines) + "\n", encoding="utf-8")

    # Manifest
    manifest = {
        "run_id": run_id,
        "original_query": question,
        "protocol_sha256": scope.protocol_sha256,
        "corpus_source": "outputs/polaris_graph/PG_LB_SA_02.json",
        "sources": {
            "count": len(classified),
            "tier_fractions": dist.tier_fractions,
            "has_material_deviation": dist.has_material_deviation,
            "approved": decision.approved,
        },
        "generator": {
            "pipeline": "multi_section",
            "outline_sections": [p.title for p in multi.outline],
            "sections_kept": sum(1 for s in multi.sections if not s.dropped_due_to_failure),
            "sections_dropped": sum(1 for s in multi.sections if s.dropped_due_to_failure),
            "regens_attempted": sum(1 for s in multi.sections if s.regen_attempted),
            "input_tokens": multi.total_input_tokens,
            "output_tokens": multi.total_output_tokens,
            "sentences_kept": multi.total_sentences_verified,
            "sentences_dropped": multi.total_sentences_dropped,
            "total_words": multi.total_words,
        },
        "contradictions_found": len(contradictions),
        "evaluator_rule_pass": ev_out.rule_check_pass_count,
        "evaluator_rule_fail": ev_out.rule_check_fail_count,
        "judge": (
            {"verdicts": jr.verdicts} if jr and jr.parse_ok
            else {"error": "failed_or_parse_error"}
        ),
    }
    (run_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    _log("")
    _log("=" * 72)
    _log("APPLES-TO-APPLES COMPLETE")
    _log("=" * 72)
    _log(f"  Honest-rebuild corpus: {len(classified)}")
    _log(f"  Tier distribution:     {tier_summary}")
    _log(f"  Contradictions:        {len(contradictions)}")
    _log(f"  Sentences verified:    {multi.total_sentences_verified} "
         f"(dropped {multi.total_sentences_dropped})")
    _log(f"  Rule checks:           {ev_out.rule_check_pass_count}/12 pass")
    if jr and jr.parse_ok:
        vcounts = {v: sum(1 for j in jr.verdicts.values() if j["verdict"] == v)
                   for v in ("good", "acceptable", "needs_revision", "unknown")}
        _log(f"  Judge verdicts:        {vcounts}")
    _log(f"  Run cost (USD):        ${current_run_cost():.4f} "
         f"(cap ${PG_MAX_COST_PER_RUN:.4f})")
    _log("")
    _log(f"  Artifacts in:          {run_dir}")
    log_f.close()
    return 0


def main() -> int:
    return asyncio.run(main_async())


if __name__ == "__main__":
    sys.exit(main())
