"""I-run11-007 (#1051): per-role OpenRouter provider routing loader.

Pins every verifier role (and, via the same config, the generator) to a ranked chain of HEALTHY,
fast providers with a deterministic fallback that NEVER routes to a broken/flaky provider — so the
Carney demo cannot land on the slow/empty providers that caused the runs-14/15/16 Mirror blanks.

The ranked order + ignore list live in `config/settings/openrouter_provider_routing.yaml`
(generated by `scripts/diagnostics/rank_openrouter_providers.py` from live endpoint health — LAW VI:
config, never inlined). This module only READS that config; it never makes a network call.

Degrades gracefully: if the config file or the role is absent, or routing is disabled via
`PG_OPENROUTER_PROVIDER_ROUTING=0`, returns None and the transport keeps its prior behavior
(`require_parameters` only). The config is committed, so production gets pinned routing by default.
"""

from __future__ import annotations

import os
from pathlib import Path

import yaml

_DEFAULT_CONFIG_PATH = "config/settings/openrouter_provider_routing.yaml"
_ENABLE_ENV = "PG_OPENROUTER_PROVIDER_ROUTING"
_CONFIG_PATH_ENV = "PG_PROVIDER_ROUTING_CONFIG"

# Cache keyed by the RESOLVED path string so a test that repoints _CONFIG_PATH_ENV picks up its
# fixture rather than a stale parse. A small YAML, so a per-distinct-path parse is cheap.
_cache: dict[str, dict] = {}


def _enabled() -> bool:
    return os.getenv(_ENABLE_ENV, "1").strip().lower() in ("1", "true", "yes", "on")


def _full_config() -> dict:
    path = os.getenv(_CONFIG_PATH_ENV, _DEFAULT_CONFIG_PATH)
    if path in _cache:
        return _cache[path]
    p = Path(path)
    data = yaml.safe_load(p.read_text(encoding="utf-8")) if p.is_file() else {}
    result = data if isinstance(data, dict) else {}
    _cache[path] = result
    return result


def _roles_config() -> dict:
    roles = _full_config().get("roles")
    return roles if isinstance(roles, dict) else {}


def slug_for_provider(provider: str | None) -> str | None:
    """Map a served `provider` DISPLAY name (OpenRouter response field, e.g. 'AtlasCloud', 'Io Net')
    back to the routing SLUG ('atlas-cloud', 'io-net') that `provider.order`/`ignore` use, via the
    config's `provider_aliases` map. Falls back to a lower/space-fold for providers not in the map.
    Returns the input unchanged if falsy. (Codex diff-gate iter-1 P1: a naive fold mis-maps camelCase
    providers, so the empty-retry could ignore an identity OpenRouter does not match -> retry the same
    blank provider.)"""
    if not provider:
        return provider
    aliases = _full_config().get("provider_aliases")
    if isinstance(aliases, dict) and provider in aliases:
        return str(aliases[provider])
    return provider.strip().lower().replace(" ", "-")


def reset_cache() -> None:
    """Drop the parsed-config cache (tests that swap the config fixture call this)."""
    _cache.clear()


def role_provider_routing(role: str) -> dict | None:
    """Return ``{"order": [slug...], "ignore": [slug...]}`` for ``role``, else ``None``.

    ``None`` means "not configured / disabled" — the caller keeps its prior provider block.
    A configured role MUST have a non-empty ``order`` (an empty order would pin nothing); an empty
    or missing ``ignore`` is fine.
    """
    if not _enabled():
        return None
    cfg = _roles_config().get(role)
    if not isinstance(cfg, dict):
        return None
    order = [str(s) for s in (cfg.get("order") or []) if str(s).strip()]
    if not order:
        return None
    ignore = [str(s) for s in (cfg.get("ignore") or []) if str(s).strip()]
    return {"order": order, "ignore": ignore}


def apply_provider_routing(provider_block: dict, role: str) -> dict:
    """Merge the role's ranked order + ignore + ``allow_fallbacks: False`` into ``provider_block``.

    ``allow_fallbacks: False`` (per the OpenRouter routing docs) restricts attempts to EXACTLY the
    listed healthy providers in rank order — OpenRouter never falls through to an unlisted flaky
    provider. ``ignore`` is the belt-and-suspenders deny-list. A pre-existing ``require_parameters``
    is preserved. No-op (returns the block unchanged) when the role is unconfigured.
    """
    routing = role_provider_routing(role)
    if routing is None:
        return provider_block
    provider_block["order"] = routing["order"]
    if routing["ignore"]:
        # merge, do not clobber, any pre-set ignore
        existing = provider_block.get("ignore") or []
        provider_block["ignore"] = list(dict.fromkeys([*existing, *routing["ignore"]]))
    provider_block["allow_fallbacks"] = False
    return provider_block
